// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using System.Collections.Generic;
using System.Text;
using System.Threading.Tasks;
using Microsoft.CodeAnalysis.Testing;
using Microsoft.CodeAnalysis.Text;
using Xunit;
using VerifyGenerator = CSharpGeneratorVerifier<CoreWCF.BuildTools.OperationInvokerGenerator>;

namespace CoreWCF.BuildTools.Tests;

public class OperationInvokerGeneratorTests
{
    private const string SSMNamespace = "System.ServiceModel";
    private const string CoreWCFNamespace = "CoreWCF";

    public static IEnumerable<object[]> GetTestVariations()
    {
        yield return new object[] { SSMNamespace };
        yield return new object[] { CoreWCFNamespace };
    }

    [Theory]
    [MemberData(nameof(GetTestVariations))]
    public async Task DefaultNonOptInTest(string attributeNamespace)
    {
        var test = new VerifyGenerator.Test
        {
            TestState =
            {
                Sources =
                {
@$"
namespace MyProject
{{
    [{attributeNamespace}.ServiceContract]
    public interface IIdentityService
    {{
        [{attributeNamespace}.OperationContract]
        string Echo(string input, ref bool b, out int i);
    }}

    public partial class IdentityService : IIdentityService
    {{
        public string Echo(string input, ref bool b, out int i)
        {{
            i = 10;
            return input;
        }}
    }}
}}
"
                }
            }
        };

        await test.RunAsync();
    }

    [Theory]
    [MemberData(nameof(GetTestVariations))]
    public async Task SimpleTest(string attributeNamespace)
    {
        var test = new VerifyGenerator.Test
        {
            TestState =
            {
                Sources =
                {
@$"
namespace MyProject
{{
    [{attributeNamespace}.ServiceContract]
    public interface IIdentityService
    {{
        [{attributeNamespace}.OperationContract]
        string Echo(string input, ref bool b, out int i);
    }}

    public partial class IdentityService : IIdentityService
    {{
        public string Echo(string input, ref bool b, out int i)
        {{
            i = 10;
            return input;
        }}
    }}
}}
"
                },
                AnalyzerConfigFiles =
                {
                    (typeof(OperationInvokerGenerator),"/.globalconfig", """
is_global = true
build_property.EnableCoreWCFOperationInvokerGenerator = true
""")
                },
                GeneratedSources =
                {
                    (typeof(OperationInvokerGenerator), "OperationInvoker.g.cs", SourceText.From($$"""
// <auto-generated>
// Generated by the CoreWCF.BuildTools.OperationInvokerGenerator source generator. DO NOT EDIT!
// </auto-generated>
#nullable disable
using System;
using System.Threading.Tasks;
namespace System.Runtime.CompilerServices
{
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = false)]
    file sealed class ModuleInitializerAttribute : Attribute { }
}
namespace CoreWCF.Dispatcher
{
    // This class is used to invoke the method MyProject.IIdentityService.Echo(string, ref bool, out int).
    file sealed class OperationInvoker0 : CoreWCF.Dispatcher.IOperationInvoker
    {
        public ValueTask<(object returnValue, object[] outputs)> InvokeAsync(object instance, object[] inputs)
        {
            string p0;
            p0 = inputs[0] == null ? default(string) : (string)inputs[0];
            bool p1;
            p1 = inputs[1] == null ? default(bool) : (bool)inputs[1];
            int p2;
            var result = ((MyProject.IIdentityService)instance).Echo(p0, ref p1, out p2);
            var outputs = AllocateOutputs();
            outputs[0] = p1;
            outputs[1] = p2;
            return new ValueTask<(object, object[])>((result, outputs));
        }

        public object[] AllocateInputs() => new object[2];

        private object[] AllocateOutputs() => new object[2];

        internal static void RegisterOperationInvoker() => CoreWCF.Dispatcher.DispatchOperationRuntimeHelpers.RegisterOperationInvoker("MyProject.IIdentityService.Echo(string, ref bool, out int)", new OperationInvoker0());
    }
}
namespace CoreWCF.Dispatcher
{
    file sealed class OperationInvokerModuleInitializer
    {
        [System.Runtime.CompilerServices.ModuleInitializer]
        internal static void RegisterOperationInvokers()
        {
            OperationInvoker0.RegisterOperationInvoker();
        }
    }
}
#nullable restore

""", Encoding.UTF8, SourceHashAlgorithm.Sha256)),
                },
            },
        };

        await test.RunAsync();
    }

    [Theory]
    [MemberData(nameof(GetTestVariations))]
    public async Task NoNamespaceTest(string attributeNamespace)
    {
        var test = new VerifyGenerator.Test
        {
            TestState =
            {
                Sources =
                {
@$"
[{attributeNamespace}.ServiceContract]
public interface IIdentityService
{{
    [{attributeNamespace}.OperationContract]
    string Echo(string input, ref bool b, out int i);
}}

public partial class IdentityService : IIdentityService
{{
    public string Echo(string input, ref bool b, out int i)
    {{
        i = 10;
        return input;
    }}
}}
"
                },
                AnalyzerConfigFiles =
                {
                    (typeof(OperationInvokerGenerator),"/.globalconfig", """
is_global = true
build_property.EnableCoreWCFOperationInvokerGenerator = true
""")
                },
                GeneratedSources =
                {
                    (typeof(OperationInvokerGenerator), "OperationInvoker.g.cs", SourceText.From($$"""
// <auto-generated>
// Generated by the CoreWCF.BuildTools.OperationInvokerGenerator source generator. DO NOT EDIT!
// </auto-generated>
#nullable disable
using System;
using System.Threading.Tasks;
namespace System.Runtime.CompilerServices
{
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = false)]
    file sealed class ModuleInitializerAttribute : Attribute { }
}
namespace CoreWCF.Dispatcher
{
    // This class is used to invoke the method IIdentityService.Echo(string, ref bool, out int).
    file sealed class OperationInvoker0 : CoreWCF.Dispatcher.IOperationInvoker
    {
        public ValueTask<(object returnValue, object[] outputs)> InvokeAsync(object instance, object[] inputs)
        {
            string p0;
            p0 = inputs[0] == null ? default(string) : (string)inputs[0];
            bool p1;
            p1 = inputs[1] == null ? default(bool) : (bool)inputs[1];
            int p2;
            var result = ((IIdentityService)instance).Echo(p0, ref p1, out p2);
            var outputs = AllocateOutputs();
            outputs[0] = p1;
            outputs[1] = p2;
            return new ValueTask<(object, object[])>((result, outputs));
        }

        public object[] AllocateInputs() => new object[2];

        private object[] AllocateOutputs() => new object[2];

        internal static void RegisterOperationInvoker() => CoreWCF.Dispatcher.DispatchOperationRuntimeHelpers.RegisterOperationInvoker("IIdentityService.Echo(string, ref bool, out int)", new OperationInvoker0());
    }
}
namespace CoreWCF.Dispatcher
{
    file sealed class OperationInvokerModuleInitializer
    {
        [System.Runtime.CompilerServices.ModuleInitializer]
        internal static void RegisterOperationInvokers()
        {
            OperationInvoker0.RegisterOperationInvoker();
        }
    }
}
#nullable restore

""", Encoding.UTF8, SourceHashAlgorithm.Sha256)),
                },
            },
        };

        await test.RunAsync();
    }

    [Theory]
    [MemberData(nameof(GetTestVariations))]
    public async Task PrivateInterfaceTest(string attributeNamespace)
    {
        var test = new VerifyGenerator.Test
        {
            TestState =
            {
                Sources =
                {
@$"
namespace MyProject
{{
[{attributeNamespace}.ServiceContract]
private interface IIdentityService
{{
    [{attributeNamespace}.OperationContract]
    string Echo(string input, ref bool b, out int i);
}}

partial class IdentityService : IIdentityService
{{
    public string Echo(string input, ref bool b, out int i)
    {{
        i = 10;
        return input;
    }}
}}
}}
"
                },
                AnalyzerConfigFiles =
                {
                    (typeof(OperationInvokerGenerator),"/.globalconfig", """
is_global = true
build_property.EnableCoreWCFOperationInvokerGenerator = true
""")
                }
            }
        };

        await test.RunAsync();
    }

    [Theory]
    [MemberData(nameof(GetTestVariations))]
    public async Task NestedPrivateInterfaceTest(string attributeNamespace)
    {
        var test = new VerifyGenerator.Test
        {
            TestState =
            {
                Sources =
                {
                    @$"
namespace MyProject
{{
private partial class Container
{{
    [{attributeNamespace}.ServiceContract]
    interface IIdentityService
    {{
        [{attributeNamespace}.OperationContract]
        string Echo(string input, ref bool b, out int i);
    }}

    partial class IdentityService : IIdentityService
    {{
        public string Echo(string input, ref bool b, out int i)
        {{
            i = 10;
            return input;
        }}
    }}
}}
}}
"
                },
                AnalyzerConfigFiles =
                {
                    (typeof(OperationInvokerGenerator),"/.globalconfig", """
                                                                         is_global = true
                                                                         build_property.EnableCoreWCFOperationInvokerGenerator = true
                                                                         """)
                }
            }
        };

        await test.RunAsync();
    }

    [Theory]
    [MemberData(nameof(GetTestVariations))]
    public async Task MultipleOperationTest(string attributeNamespace)
    {
        var test = new VerifyGenerator.Test
        {
            TestState =
            {
                Sources =
                {
@$"
namespace MyProject
{{
[{attributeNamespace}.ServiceContract]
public interface IIdentityService
{{
    [{attributeNamespace}.OperationContract]
    string Echo(string input, ref bool b, out int i);
    [{attributeNamespace}.OperationContract]
    string Echo2(string input, ref bool b, out int i);
}}

public partial class IdentityService : IIdentityService
{{
    public string Echo(string input, ref bool b, out int i)
    {{
        i = 10;
        return input;
    }}
    public string Echo2(string input, ref bool b, out int i)
    {{
        i = 10;
        return input;
    }}
}}
}}
"
                },
                AnalyzerConfigFiles =
                {
                    (typeof(OperationInvokerGenerator),"/.globalconfig", """
is_global = true
build_property.EnableCoreWCFOperationInvokerGenerator = true
""")
                },
                GeneratedSources =
                {
                    (typeof(OperationInvokerGenerator), "OperationInvoker.g.cs", SourceText.From($$"""
// <auto-generated>
// Generated by the CoreWCF.BuildTools.OperationInvokerGenerator source generator. DO NOT EDIT!
// </auto-generated>
#nullable disable
using System;
using System.Threading.Tasks;
namespace System.Runtime.CompilerServices
{
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = false)]
    file sealed class ModuleInitializerAttribute : Attribute { }
}
namespace CoreWCF.Dispatcher
{
    // This class is used to invoke the method MyProject.IIdentityService.Echo(string, ref bool, out int).
    file sealed class OperationInvoker0 : CoreWCF.Dispatcher.IOperationInvoker
    {
        public ValueTask<(object returnValue, object[] outputs)> InvokeAsync(object instance, object[] inputs)
        {
            string p0;
            p0 = inputs[0] == null ? default(string) : (string)inputs[0];
            bool p1;
            p1 = inputs[1] == null ? default(bool) : (bool)inputs[1];
            int p2;
            var result = ((MyProject.IIdentityService)instance).Echo(p0, ref p1, out p2);
            var outputs = AllocateOutputs();
            outputs[0] = p1;
            outputs[1] = p2;
            return new ValueTask<(object, object[])>((result, outputs));
        }

        public object[] AllocateInputs() => new object[2];

        private object[] AllocateOutputs() => new object[2];

        internal static void RegisterOperationInvoker() => CoreWCF.Dispatcher.DispatchOperationRuntimeHelpers.RegisterOperationInvoker("MyProject.IIdentityService.Echo(string, ref bool, out int)", new OperationInvoker0());
    }
}
namespace CoreWCF.Dispatcher
{
    // This class is used to invoke the method MyProject.IIdentityService.Echo2(string, ref bool, out int).
    file sealed class OperationInvoker1 : CoreWCF.Dispatcher.IOperationInvoker
    {
        public ValueTask<(object returnValue, object[] outputs)> InvokeAsync(object instance, object[] inputs)
        {
            string p0;
            p0 = inputs[0] == null ? default(string) : (string)inputs[0];
            bool p1;
            p1 = inputs[1] == null ? default(bool) : (bool)inputs[1];
            int p2;
            var result = ((MyProject.IIdentityService)instance).Echo2(p0, ref p1, out p2);
            var outputs = AllocateOutputs();
            outputs[0] = p1;
            outputs[1] = p2;
            return new ValueTask<(object, object[])>((result, outputs));
        }

        public object[] AllocateInputs() => new object[2];

        private object[] AllocateOutputs() => new object[2];

        internal static void RegisterOperationInvoker() => CoreWCF.Dispatcher.DispatchOperationRuntimeHelpers.RegisterOperationInvoker("MyProject.IIdentityService.Echo2(string, ref bool, out int)", new OperationInvoker1());
    }
}
namespace CoreWCF.Dispatcher
{
    file sealed class OperationInvokerModuleInitializer
    {
        [System.Runtime.CompilerServices.ModuleInitializer]
        internal static void RegisterOperationInvokers()
        {
            OperationInvoker0.RegisterOperationInvoker();
            OperationInvoker1.RegisterOperationInvoker();
        }
    }
}
#nullable restore

""", Encoding.UTF8, SourceHashAlgorithm.Sha256)),
                },
            },
        };

        await test.RunAsync();
    }

    [Theory]
    [MemberData(nameof(GetTestVariations))]
    public async Task IntegratedTypesAsDotNetTypesTest(string attributeNamespace)
    {
        var test = new VerifyGenerator.Test
        {
            TestState =
            {
                Sources =
                {
@$"
namespace MyProject
{{
[{attributeNamespace}.ServiceContract]
public interface IIdentityService
{{
    [{attributeNamespace}.OperationContract]
    System.String Echo(System.String input, ref System.Boolean b, out System.Int32 i);
}}

public partial class IdentityService : IIdentityService
{{
    public System.String Echo(System.String input, ref System.Boolean b, out System.Int32 i)
    {{
        i = 10;
        return input;
    }}
}}
}}
"
                },
                AnalyzerConfigFiles =
                {
                    (typeof(OperationInvokerGenerator),"/.globalconfig", """
is_global = true
build_property.EnableCoreWCFOperationInvokerGenerator = true
""")
                },
                GeneratedSources =
                {
                    (typeof(OperationInvokerGenerator), "OperationInvoker.g.cs", SourceText.From($$"""
// <auto-generated>
// Generated by the CoreWCF.BuildTools.OperationInvokerGenerator source generator. DO NOT EDIT!
// </auto-generated>
#nullable disable
using System;
using System.Threading.Tasks;
namespace System.Runtime.CompilerServices
{
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = false)]
    file sealed class ModuleInitializerAttribute : Attribute { }
}
namespace CoreWCF.Dispatcher
{
    // This class is used to invoke the method MyProject.IIdentityService.Echo(string, ref bool, out int).
    file sealed class OperationInvoker0 : CoreWCF.Dispatcher.IOperationInvoker
    {
        public ValueTask<(object returnValue, object[] outputs)> InvokeAsync(object instance, object[] inputs)
        {
            string p0;
            p0 = inputs[0] == null ? default(string) : (string)inputs[0];
            bool p1;
            p1 = inputs[1] == null ? default(bool) : (bool)inputs[1];
            int p2;
            var result = ((MyProject.IIdentityService)instance).Echo(p0, ref p1, out p2);
            var outputs = AllocateOutputs();
            outputs[0] = p1;
            outputs[1] = p2;
            return new ValueTask<(object, object[])>((result, outputs));
        }

        public object[] AllocateInputs() => new object[2];

        private object[] AllocateOutputs() => new object[2];

        internal static void RegisterOperationInvoker() => CoreWCF.Dispatcher.DispatchOperationRuntimeHelpers.RegisterOperationInvoker("MyProject.IIdentityService.Echo(string, ref bool, out int)", new OperationInvoker0());
    }
}
namespace CoreWCF.Dispatcher
{
    file sealed class OperationInvokerModuleInitializer
    {
        [System.Runtime.CompilerServices.ModuleInitializer]
        internal static void RegisterOperationInvokers()
        {
            OperationInvoker0.RegisterOperationInvoker();
        }
    }
}
#nullable restore

""", Encoding.UTF8, SourceHashAlgorithm.Sha256)),
                },
            },
        };

        await test.RunAsync();
    }

    [Theory]
    [MemberData(nameof(GetTestVariations))]
    public async Task GenericsTest(string attributeNamespace)
    {
        var test = new VerifyGenerator.Test
        {
            TestState =
            {
                Sources =
                {
@$"
namespace MyProject
{{
    [{attributeNamespace}.ServiceContract]
    public interface IIdentityService
    {{
        [{attributeNamespace}.OperationContract]
        string Echo(System.Collections.Generic.List<string> inputs);
    }}

    public partial class IdentityService : IIdentityService
    {{
        public string Echo(System.Collections.Generic.List<string> inputs)
        {{
            return input[0];
        }}
    }}
}}
"
                },
                AnalyzerConfigFiles =
                {
                    (typeof(OperationInvokerGenerator),"/.globalconfig", """
is_global = true
build_property.EnableCoreWCFOperationInvokerGenerator = true
""")
                },
                GeneratedSources =
                {
                    (typeof(OperationInvokerGenerator), "OperationInvoker.g.cs", SourceText.From($$"""
// <auto-generated>
// Generated by the CoreWCF.BuildTools.OperationInvokerGenerator source generator. DO NOT EDIT!
// </auto-generated>
#nullable disable
using System;
using System.Threading.Tasks;
namespace System.Runtime.CompilerServices
{
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = false)]
    file sealed class ModuleInitializerAttribute : Attribute { }
}
namespace CoreWCF.Dispatcher
{
    // This class is used to invoke the method MyProject.IIdentityService.Echo(System.Collections.Generic.List<string>).
    file sealed class OperationInvoker0 : CoreWCF.Dispatcher.IOperationInvoker
    {
        public ValueTask<(object returnValue, object[] outputs)> InvokeAsync(object instance, object[] inputs)
        {
            System.Collections.Generic.List<string> p0;
            p0 = inputs[0] == null ? default(System.Collections.Generic.List<string>) : (System.Collections.Generic.List<string>)inputs[0];
            var result = ((MyProject.IIdentityService)instance).Echo(p0);
            var outputs = AllocateOutputs();
            return new ValueTask<(object, object[])>((result, outputs));
        }

        public object[] AllocateInputs() => new object[1];

        private object[] AllocateOutputs() => Array.Empty<object>();

        internal static void RegisterOperationInvoker() => CoreWCF.Dispatcher.DispatchOperationRuntimeHelpers.RegisterOperationInvoker("MyProject.IIdentityService.Echo(System.Collections.Generic.List<string>)", new OperationInvoker0());
    }
}
namespace CoreWCF.Dispatcher
{
    file sealed class OperationInvokerModuleInitializer
    {
        [System.Runtime.CompilerServices.ModuleInitializer]
        internal static void RegisterOperationInvokers()
        {
            OperationInvoker0.RegisterOperationInvoker();
        }
    }
}
#nullable restore

""", Encoding.UTF8, SourceHashAlgorithm.Sha256)),
                },
            },
        };

        await test.RunAsync();
    }

    [Theory]
    [MemberData(nameof(GetTestVariations))]
    public async Task ParamsArrayTest(string attributeNamespace)
    {
        var test = new VerifyGenerator.Test
        {
            TestState =
            {
                Sources =
                {
@$"
namespace MyProject
{{
    [{attributeNamespace}.ServiceContract]
    public interface IIdentityService
    {{
        [{attributeNamespace}.OperationContract]
        string Echo(params string[] inputs);
    }}

    public partial class IdentityService : IIdentityService
    {{
        public string Echo(params string[] inputs)
        {{
            return input[0];
        }}
    }}
}}
"
                },
                AnalyzerConfigFiles =
                {
                    (typeof(OperationInvokerGenerator),"/.globalconfig", """
is_global = true
build_property.EnableCoreWCFOperationInvokerGenerator = true
""")
                },
                GeneratedSources =
                {
                    (typeof(OperationInvokerGenerator), "OperationInvoker.g.cs", SourceText.From($$"""
// <auto-generated>
// Generated by the CoreWCF.BuildTools.OperationInvokerGenerator source generator. DO NOT EDIT!
// </auto-generated>
#nullable disable
using System;
using System.Threading.Tasks;
namespace System.Runtime.CompilerServices
{
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = false)]
    file sealed class ModuleInitializerAttribute : Attribute { }
}
namespace CoreWCF.Dispatcher
{
    // This class is used to invoke the method MyProject.IIdentityService.Echo(params string[]).
    file sealed class OperationInvoker0 : CoreWCF.Dispatcher.IOperationInvoker
    {
        public ValueTask<(object returnValue, object[] outputs)> InvokeAsync(object instance, object[] inputs)
        {
            string[] p0;
            p0 = inputs[0] == null ? default(string[]) : (string[])inputs[0];
            var result = ((MyProject.IIdentityService)instance).Echo(p0);
            var outputs = AllocateOutputs();
            return new ValueTask<(object, object[])>((result, outputs));
        }

        public object[] AllocateInputs() => new object[1];

        private object[] AllocateOutputs() => Array.Empty<object>();

        internal static void RegisterOperationInvoker() => CoreWCF.Dispatcher.DispatchOperationRuntimeHelpers.RegisterOperationInvoker("MyProject.IIdentityService.Echo(params string[])", new OperationInvoker0());
    }
}
namespace CoreWCF.Dispatcher
{
    file sealed class OperationInvokerModuleInitializer
    {
        [System.Runtime.CompilerServices.ModuleInitializer]
        internal static void RegisterOperationInvokers()
        {
            OperationInvoker0.RegisterOperationInvoker();
        }
    }
}
#nullable restore

""", Encoding.UTF8, SourceHashAlgorithm.Sha256)),
                },
            },
        };

        await test.RunAsync();
    }

    [Theory]
    [MemberData(nameof(GetTestVariations))]
    public async Task ReturnsVoidTest(string attributeNamespace)
    {
        var test = new VerifyGenerator.Test
        {
            TestState =
            {
                Sources =
                {
@$"
namespace MyProject
{{
    [{attributeNamespace}.ServiceContract]
    public interface IIdentityService
    {{
        [{attributeNamespace}.OperationContract]
        void Echo(string input);
    }}

    public partial class IdentityService : IIdentityService
    {{
        public void Echo(string input)
        {{

        }}
    }}
}}
"
                },
                AnalyzerConfigFiles =
                {
                    (typeof(OperationInvokerGenerator),"/.globalconfig", """
is_global = true
build_property.EnableCoreWCFOperationInvokerGenerator = true
""")
                },
                GeneratedSources =
                {
                    (typeof(OperationInvokerGenerator), "OperationInvoker.g.cs", SourceText.From($$"""
// <auto-generated>
// Generated by the CoreWCF.BuildTools.OperationInvokerGenerator source generator. DO NOT EDIT!
// </auto-generated>
#nullable disable
using System;
using System.Threading.Tasks;
namespace System.Runtime.CompilerServices
{
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = false)]
    file sealed class ModuleInitializerAttribute : Attribute { }
}
namespace CoreWCF.Dispatcher
{
    // This class is used to invoke the method MyProject.IIdentityService.Echo(string).
    file sealed class OperationInvoker0 : CoreWCF.Dispatcher.IOperationInvoker
    {
        public ValueTask<(object returnValue, object[] outputs)> InvokeAsync(object instance, object[] inputs)
        {
            string p0;
            p0 = inputs[0] == null ? default(string) : (string)inputs[0];
            ((MyProject.IIdentityService)instance).Echo(p0);
            var outputs = AllocateOutputs();
            return new ValueTask<(object, object[])>((null, outputs));
        }

        public object[] AllocateInputs() => new object[1];

        private object[] AllocateOutputs() => Array.Empty<object>();

        internal static void RegisterOperationInvoker() => CoreWCF.Dispatcher.DispatchOperationRuntimeHelpers.RegisterOperationInvoker("MyProject.IIdentityService.Echo(string)", new OperationInvoker0());
    }
}
namespace CoreWCF.Dispatcher
{
    file sealed class OperationInvokerModuleInitializer
    {
        [System.Runtime.CompilerServices.ModuleInitializer]
        internal static void RegisterOperationInvokers()
        {
            OperationInvoker0.RegisterOperationInvoker();
        }
    }
}
#nullable restore

""", Encoding.UTF8, SourceHashAlgorithm.Sha256)),
                },
            },
        };

        await test.RunAsync();
    }

    [Theory]
    [MemberData(nameof(GetTestVariations))]
    public async Task ReturnsTaskTest(string attributeNamespace)
    {
        var test = new VerifyGenerator.Test
        {
            TestState =
            {
                Sources =
                {
@$"
namespace MyProject
{{
    [{attributeNamespace}.ServiceContract]
    public interface IIdentityService
    {{
        [{attributeNamespace}.OperationContract]
        System.Threading.Tasks.Task Echo(string input);
    }}

    public partial class IdentityService : IIdentityService
    {{
        public System.Threading.Tasks.Task Echo(string input)
        {{
            return System.Threading.Tasks.Task.CompletedTask;
        }}
    }}
}}
"
                },
                AnalyzerConfigFiles =
                {
                    (typeof(OperationInvokerGenerator),"/.globalconfig", """
is_global = true
build_property.EnableCoreWCFOperationInvokerGenerator = true
""")
                },
                GeneratedSources =
                {
                    (typeof(OperationInvokerGenerator), "OperationInvoker.g.cs", SourceText.From($$"""
// <auto-generated>
// Generated by the CoreWCF.BuildTools.OperationInvokerGenerator source generator. DO NOT EDIT!
// </auto-generated>
#nullable disable
using System;
using System.Threading.Tasks;
namespace System.Runtime.CompilerServices
{
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = false)]
    file sealed class ModuleInitializerAttribute : Attribute { }
}
namespace CoreWCF.Dispatcher
{
    // This class is used to invoke the method MyProject.IIdentityService.Echo(string).
    file sealed class OperationInvoker0 : CoreWCF.Dispatcher.IOperationInvoker
    {
        public async ValueTask<(object returnValue, object[] outputs)> InvokeAsync(object instance, object[] inputs)
        {
            string p0;
            p0 = inputs[0] == null ? default(string) : (string)inputs[0];
            await ((MyProject.IIdentityService)instance).Echo(p0);
            var outputs = AllocateOutputs();
            return (null, outputs);
        }

        public object[] AllocateInputs() => new object[1];

        private object[] AllocateOutputs() => Array.Empty<object>();

        internal static void RegisterOperationInvoker() => CoreWCF.Dispatcher.DispatchOperationRuntimeHelpers.RegisterOperationInvoker("MyProject.IIdentityService.Echo(string)", new OperationInvoker0());
    }
}
namespace CoreWCF.Dispatcher
{
    file sealed class OperationInvokerModuleInitializer
    {
        [System.Runtime.CompilerServices.ModuleInitializer]
        internal static void RegisterOperationInvokers()
        {
            OperationInvoker0.RegisterOperationInvoker();
        }
    }
}
#nullable restore

""", Encoding.UTF8, SourceHashAlgorithm.Sha256)),
                },
            },
        };

        await test.RunAsync();
    }

    [Theory]
    [MemberData(nameof(GetTestVariations))]
    public async Task ReturnsGenericTaskTest(string attributeNamespace)
    {
        var test = new VerifyGenerator.Test
        {
            TestState =
            {
                Sources =
                {
@$"
namespace MyProject
{{
    [{attributeNamespace}.ServiceContract]
    public interface IIdentityService
    {{
        [{attributeNamespace}.OperationContract]
        System.Threading.Tasks.Task<string> Echo(string input);
    }}

    public partial class IdentityService : IIdentityService
    {{
        public System.Threading.Tasks.Task<string> Echo(string input)
        {{
            return System.Threading.Tasks.Task.FromResult(input);
        }}
    }}
}}
"
                },
                AnalyzerConfigFiles =
                {
                    (typeof(OperationInvokerGenerator),"/.globalconfig", """
is_global = true
build_property.EnableCoreWCFOperationInvokerGenerator = true
""")
                },
                GeneratedSources =
                {
                    (typeof(OperationInvokerGenerator), "OperationInvoker.g.cs", SourceText.From($$"""
// <auto-generated>
// Generated by the CoreWCF.BuildTools.OperationInvokerGenerator source generator. DO NOT EDIT!
// </auto-generated>
#nullable disable
using System;
using System.Threading.Tasks;
namespace System.Runtime.CompilerServices
{
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = false)]
    file sealed class ModuleInitializerAttribute : Attribute { }
}
namespace CoreWCF.Dispatcher
{
    // This class is used to invoke the method MyProject.IIdentityService.Echo(string).
    file sealed class OperationInvoker0 : CoreWCF.Dispatcher.IOperationInvoker
    {
        public async ValueTask<(object returnValue, object[] outputs)> InvokeAsync(object instance, object[] inputs)
        {
            string p0;
            p0 = inputs[0] == null ? default(string) : (string)inputs[0];
            var result = await ((MyProject.IIdentityService)instance).Echo(p0);
            var outputs = AllocateOutputs();
            return (result, outputs);
        }

        public object[] AllocateInputs() => new object[1];

        private object[] AllocateOutputs() => Array.Empty<object>();

        internal static void RegisterOperationInvoker() => CoreWCF.Dispatcher.DispatchOperationRuntimeHelpers.RegisterOperationInvoker("MyProject.IIdentityService.Echo(string)", new OperationInvoker0());
    }
}
namespace CoreWCF.Dispatcher
{
    file sealed class OperationInvokerModuleInitializer
    {
        [System.Runtime.CompilerServices.ModuleInitializer]
        internal static void RegisterOperationInvokers()
        {
            OperationInvoker0.RegisterOperationInvoker();
        }
    }
}
#nullable restore

""", Encoding.UTF8, SourceHashAlgorithm.Sha256)),
                },
            },
        };

        await test.RunAsync();
    }
}

