<Project Sdk="Microsoft.NET.Sdk" ToolsVersion="15.0">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>CoreWCF.WebHttp</AssemblyName>
    <PackageId>CoreWCF.WebHttp</PackageId>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <RootNamespace />
    <GenerateEmbeddedFilesManifest>true</GenerateEmbeddedFilesManifest>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore.Swagger" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="$(SourceDir)CoreWCF.Http\src\CoreWCF.Http.csproj" />
  </ItemGroup>
</Project>
