trigger: none

pr:
  branches:
    include:
    - main
    - release/*
    - feature/*
  paths:
    include:
    - src/CoreWCF.Templates/

variables:
  _solution: src/CoreWCF.Templates.sln
  _libraryProjects: src/CoreWCF.Templates/src/CoreWCF.Templates.csproj
  _testProjects: src/CoreWCF.Templates.Tests.csproj

stages:
- template: templates/BuildStage.yml
  parameters:
    buildProjects: $(_libraryProjects)

- template: templates/TestTemplatesStage.yml
  parameters:
    libraryProjects: $(_libraryProjects)
