trigger: none

pr:
  branches:
    include:
    - main
    - release/*
    - feature/*

variables:
  _solutions: CoreWCFTemplates.sln
  _libraryProjects: src/CoreWCF.Templates/src/CoreWCF.Templates.csproj
  _testProjects: src/CoreWCF.Templates.Tests.csproj

stages:
- template: templates/BuildStage.yml
  parameters:
    solutions: $(_solutions)

- template: templates/TestTemplatesStage.yml
