<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>CoreWCF.RabbitMQ.Client</AssemblyName>
    <PackageId>CoreWCF.RabbitMQ.Client</PackageId>
    <RootNamespace />
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="RabbitMQ.Client" />
    <PackageReference Include="System.ServiceModel.Primitives" />
  </ItemGroup>

</Project>
