parameters:
- name: solutions
  default: ''

stages:
- stage: Build
  displayName: Build
  jobs:
  - job: Build
    strategy:
      matrix:
        WindowsRelease:
          configuration: 'Release'
          imageName: 'windows-latest'
          artifactName: 'WindowsReleaseBuild'
        WindowsDebug:
          configuration: 'Debug'
          imageName: 'windows-latest'
          artifactName: 'WindowsDebugBuild'
        LinuxRelease:
          configuration: 'Release'
          imageName: 'ubuntu-latest'
          artifactName: 'LinuxReleaseBuild'
        LinuxDebug:
          configuration: 'Debug'
          imageName: 'ubuntu-latest'
          artifactName: 'LinuxDebugBuild'
    pool:
      vmImage: $(imageName)
    steps:
      - task: UseDotNet@2
        displayName: 'Use .NET 8 sdk'
        inputs:
          packageType: sdk
          version: 8.0.x
          installationPath: $(Agent.ToolsDirectory)/dotnet
          includePreviewVersions: true

      # NGBV project at https://github.com/dotnet/Nerdbank.GitVersioning
      - task: DotNetCoreCLI@2
        inputs:
          command: custom
          custom: tool
          arguments: install --tool-path . nbgv
        displayName: Install NBGV tool

      - script: nbgv cloud
        displayName: Set Version

      - task: DotNetCoreCLI@2
        displayName: Restore
        inputs:
          command: restore
          feedsToUse: config
          nugetConfigPath: NuGet.config
          projects: ${{ parameters.solutions }}

      - task: DotNetCoreCLI@2
        displayName: Build $(configuration)
        inputs:
          command: 'build'
          projects: ${{ parameters.solutions }}
          arguments: '--no-restore -c $(configuration)'
      - publish: $(System.DefaultWorkingDirectory)/bin
        artifact: $(artifactName)