parameters:
- name: testProjects
  default: ''
- name: solutions
  default: ''

stages:
- stage: Code_Analysis
  displayName: Run Code Analysis
  dependsOn: []
  jobs:

  - job: Code_Analysis
    displayName: SonarCloud & CodeCoverage reports
    pool:
      vmImage: 'ubuntu-latest'
    steps:

    - task: UseDotNet@2
      displayName: 'Use .NET 10 sdk'
      inputs:
        packageType: sdk
        version: '10.0.x'
        includePreviewVersions: true
        installationPath: $(Agent.ToolsDirectory)/dotnet

    - task: DotNetCoreCLI@2
      displayName: Restore packages
      inputs:
        command: restore
        feedsToUse: config
        nugetConfigPath: NuGet.config
        projects: ${{ parameters.solutions }}

    - task: SonarCloudPrepare@4
      displayName: 'Prepare analysis on SonarCloud'
      inputs:
        SonarCloud: SonarCloud
        organization: corewcf
        scannerMode: dotnet
        projectKey: CoreWCF_CoreWCF
        projectName: 'CoreWCF Code Analysis'
        extraProperties: |
          sonar.cs.opencover.reportsPaths=$(Agent.TempDirectory)/**/coverage.opencover.xml
          sonar.exclusions=src/Samples/**/*.*
          sonar.coverage.exclusions=src/**/tests/**/*.cs
      condition: not(eq(variables['build.reason'], 'PullRequest'))

    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: build
        projects: ${{ parameters.solutions }}
        arguments: '--no-restore -c Release'

    - task: DotNetCoreCLI@2
      displayName: Run tests with Coverage
      timeoutInMinutes: 40
      inputs:
        command: test
        projects: ${{ parameters.testProjects }}
        arguments: '--no-restore --no-build -c Release -f net10.0 --collect:"XPlat Code Coverage" --settings coverlet.runsettings'

    - task: PublishCodeCoverageResults@1
      displayName: Publish Code Coverage report
      inputs:
        codeCoverageTool: 'Cobertura'
        summaryFileLocation: $(Agent.TempDirectory)/**/coverage.cobertura.xml

    - task: SonarCloudAnalyze@4
      displayName: 'Run SonarCloud analysis'
      condition: not(eq(variables['build.reason'], 'PullRequest'))

    - task: SonarCloudPublish@4
      displayName: 'Publish results on build summary'
      inputs:
        pollingTimeoutSec: '300'
      condition: not(eq(variables['build.reason'], 'PullRequest'))

