parameters:
- name: testProjects
  default: ''
- name: configurations
  default: Debug,Release

stages:
- stage: Test
  displayName: Run Tests
  dependsOn: Build
  jobs:
  - ${{ each configuration in split(parameters.configurations, ',') }}:
    - job: Test${{ configuration }}
      strategy:
        matrix:
          Windows_net8.0:
            imageName: 'windows-latest'
            targetFramework: 'net8.0'
            testArgs: ''
            dotnetSdk: '8.0.x'
            artifactName: 'Windows${{ configuration }}Build'
          Windows_net9.0:
            imageName: 'windows-latest'
            targetFramework: 'net9.0'
            testArgs: ''
            dotnetSdk: '9.0.x'
            artifactName: 'Windows${{ configuration }}Build'   
          Windows_net10.0:
            imageName: 'windows-latest'
            targetFramework: 'net10.0'
            testArgs: ''
            dotnetSdk: '10.0.x'
            artifactName: 'Windows${{ configuration }}Build'                        
          Windows_netfx:
            imageName: 'windows-latest'
            targetFramework: 'net472'
            testArgs: ''
            dotnetSdk: '9.0.x'
            artifactName: 'Windows${{ configuration }}Build'
          Linux_net8.0:
            imageName: 'ubuntu-latest'
            targetFramework: 'net8.0'
            testArgs: ''
            dotnetSdk: '8.0.x'
            artifactName: 'Linux${{ configuration }}Build'
          Linux_net9.0:
            imageName: 'ubuntu-latest'
            targetFramework: 'net9.0'
            testArgs: ''
            dotnetSdk: '9.0.x'
            artifactName: 'Linux${{ configuration }}Build'            
          Linux_net10.0:
            imageName: 'ubuntu-latest'
            targetFramework: 'net10.0'
            testArgs: ''
            dotnetSdk: '10.0.x'
            artifactName: 'Linux${{ configuration }}Build'                        
      displayName: Test ${{ configuration }}
      pool:
        vmImage: $(imageName)
      variables:
        ci: true
      steps:
      - task: DownloadPipelineArtifact@2
        displayName: Download build artifacts
        inputs:
          source: current
          artifact: $(artifactName)
          path: $(System.DefaultWorkingDirectory)/bin

      - task: UseDotNet@2
        displayName: 'Use .NET sdk 10.0.x'
        inputs:
          packageType: sdk
          version: 10.0.x
          installationPath: $(Agent.ToolsDirectory)/dotnet
          includePreviewVersions: true

      - task: UseDotNet@2
        displayName: 'Use Additional .NET sdk $(dotnetSdk)'
        condition: and(succeeded(), ne(variables.dotnetSdk, '10.0.x'))
        inputs:
          packageType: sdk
          version: $(dotnetSdk)
          installationPath: $(Agent.ToolsDirectory)/dotnet
          includePreviewVersions: true

      - script: |
          "%ProgramFiles%\IIS Express\IisExpressAdminCmd.exe" setupdefaulturls
        name: SetupIISExpressCertificates
        displayName: Setup IIS Express certificates for HTTPS tests
        condition: eq(variables.imageName, 'windows-latest')
        continueOnError: true
        timeoutInMinutes: 2

      - task: DotNetCoreCLI@2
        displayName: Run Tests
        timeoutInMinutes: 30
        inputs:
          command: 'test'
          projects: ${{ parameters.testProjects }}
          publishTestResults: true
          arguments: '--no-restore --no-build -c ${{ configuration }} -f $(targetFramework) $(testArgs)'

