parameters:
- name: testProjects
  default: ''
- name: configurations
  default: Debug,Release

stages:
- stage: Test
  displayName: Run Tests
  dependsOn: Build
  jobs:
  - ${{ each configuration in split(parameters.configurations, ',') }}:
    - job: Test${{ configuration }}
      strategy:
        matrix:
          Windows_net6.0:
            imageName: 'windows-latest'
            targetFramework: 'net6.0'
            testArgs: ''
            dotnetSdk: '6.0.x'
            artifactName: 'Windows${{ configuration }}Build'
          Windows_net8.0:
            imageName: 'windows-latest'
            targetFramework: 'net8.0'
            testArgs: ''
            dotnetSdk: '8.0.x'
            artifactName: 'Windows${{ configuration }}Build'
          Windows_net9.0:
            imageName: 'windows-latest'
            targetFramework: 'net9.0'
            testArgs: ''
            dotnetSdk: '9.0.x'
            artifactName: 'Windows${{ configuration }}Build'            
          Windows_netfx:
            imageName: 'windows-latest'
            targetFramework: 'net472'
            testArgs: ''
            dotnetSdk: '8.0.x'
            artifactName: 'Windows${{ configuration }}Build'
          Linux_net6.0:
            imageName: 'ubuntu-latest'
            targetFramework: 'net6.0'
            testArgs: ''
            dotnetSdk: '6.0.x'
            artifactName: 'Linux${{ configuration }}Build'
          Linux_net8.0:
            imageName: 'ubuntu-latest'
            targetFramework: 'net8.0'
            testArgs: ''
            dotnetSdk: '8.0.x'
            artifactName: 'Linux${{ configuration }}Build'
          Linux_net9.0:
            imageName: 'ubuntu-latest'
            targetFramework: 'net9.0'
            testArgs: ''
            dotnetSdk: '9.0.x'
            artifactName: 'Linux${{ configuration }}Build'            
      displayName: Test ${{ configuration }}
      pool:
        vmImage: $(imageName)
      variables:
        ci: true
      steps:
      - bash: |
          echo 'Starting docker services...'
          docker compose up -d
        name: DockerComposeLinuxServices
        displayName: Start services hosted by linux containers
        condition: eq(variables.imageName, 'ubuntu-latest')
        timeoutInMinutes: 5
        retryCountOnTaskFailure: 2

      - task: DownloadPipelineArtifact@2
        displayName: Download build artifacts
        inputs:
          source: current
          artifact: $(artifactName)
          path: $(System.DefaultWorkingDirectory)/bin

      - task: UseDotNet@2
        displayName: 'Use .NET sdk $(dotnetSdk)'
        inputs:
          packageType: sdk
          version: $(dotnetSdk)
          installationPath: $(Agent.ToolsDirectory)/dotnet
          includePreviewVersions: true

      - task: DotNetCoreCLI@2
        displayName: Run Tests
        timeoutInMinutes: 25
        inputs:
          command: 'test'
          projects: ${{ parameters.testProjects }}
          publishTestResults: true
          arguments: '--no-restore --no-build -c ${{ configuration }} -f $(targetFramework) $(testArgs)'

      - bash: |
          echo 'Cleaning up docker services...'
          docker compose down --rmi all
        name: DockerComposeDownLinuxServices
        displayName: Clean up containers used to host services
        condition: eq(variables.imageName, 'ubuntu-latest')
        timeoutInMinutes: 5
        retryCountOnTaskFailure: 2

