parameters:
- name: testProjects
  default: ''

stages:
- stage: Test
  displayName: Run Tests
  dependsOn: Build
  jobs:
  - job: TestRelease
    strategy:
      matrix:
        Windows_netcore3.1:
          imageName: 'windows-latest'
          targetFramework: 'netcoreapp3.1'
          testArgs: ''
          additionalDotNetCoreSdk: '3.1.x'
        Windows_net5.0:
          imageName: 'windows-latest'
          targetFramework: 'net5.0'
          testArgs: ''
          additionalDotNetCoreSdk: '5.0.x'
        Windows_net6.0:
          imageName: 'windows-latest'
          targetFramework: 'net6.0'
          testArgs: ''
          additionalDotNetCoreSdk: ''
        Windows_netfx:
          imageName: 'windows-latest'
          targetFramework: 'net472'
          testArgs: '--filter Category!=NetCoreOnly'
          additionalDotNetCoreSdk: ''
        Linux_netcore3.1:
          imageName: 'ubuntu-latest'
          targetFramework: 'netcoreapp3.1'
          testArgs: '--filter Category!=WindowsOnly'
          additionalDotNetCoreSdk: '3.1.x'
        Linux_net5.0:
          imageName: 'ubuntu-latest'
          targetFramework: 'net5.0'
          testArgs: '--filter Category!=WindowsOnly'
          additionalDotNetCoreSdk: '5.0.x'
        Linux_net6.0:
          imageName: 'ubuntu-latest'
          targetFramework: 'net6.0'
          testArgs: '--filter Category!=WindowsOnly'
          additionalDotNetCoreSdk: ''
    displayName: Test Release
    pool:
      vmImage: $(imageName)
    steps:
    - task: DownloadPipelineArtifact@2
      displayName: Download build artifacts
      inputs:
        source: current
        artifact: ReleaseBuild
        path: $(System.DefaultWorkingDirectory)/bin

    - task: UseDotNet@2
      displayName: 'Use .NET Core 6 sdk'
      inputs:
        packageType: sdk
        version: '6.0.x'
        installationPath: $(Agent.ToolsDirectory)/dotnet

    - task: UseDotNet@2
      displayName: 'Use additional .NET Core sdk'
      inputs:
        packageType: sdk
        version: $(additionalDotNetCoreSdk)
        installationPath: $(Agent.ToolsDirectory)/dotnet
      condition: not(eq(variables.additionalDotNetCoreSdk, ''))

    - task: DotNetCoreCLI@2
      displayName: Restore packages
      inputs:
        command: 'build'
        projects: ${{ parameters.testProjects}}
        arguments: '--configuration Release /t:restore'

    - task: DotNetCoreCLI@2
      displayName: Build test projects
      inputs:
        command: 'build'
        projects: ${{ parameters.testProjects}}
        arguments: '--configuration Release --framework $(targetFramework)'

    - task: DotNetCoreCLI@2
      displayName: Run Tests
      timeoutInMinutes: 15
      inputs:
        command: 'test'
        projects: ${{ parameters.testProjects}}
        publishTestResults: true
        arguments: '--no-restore --no-build --configuration Release --framework $(targetFramework) $(testArgs)'

  - job: TestDebug
    strategy:
      matrix:
        Windows_netcore3.1:
          imageName: 'windows-latest'
          targetFramework: 'netcoreapp3.1'
          testArgs: ''       
          additionalDotNetCoreSdk: '3.1.x'
        Windows_net5.0:
          imageName: 'windows-latest'
          targetFramework: 'net5.0'
          testArgs: ''
          additionalDotNetCoreSdk: '5.0.x'
        Windows_net6.0:
          imageName: 'windows-latest'
          targetFramework: 'net6.0'
          testArgs: ''
          additionalDotNetCoreSdk: ''
        Windows_netfx:
          imageName: 'windows-latest'
          targetFramework: 'net472'
          testArgs: '--filter Category!=NetCoreOnly'
          additionalDotNetCoreSdk: ''
        Linux_netcore3.1:
          imageName: 'ubuntu-latest'
          targetFramework: 'netcoreapp3.1'
          testArgs: '--filter Category!=WindowsOnly'
          additionalDotNetCoreSdk: '3.1.x'
        Linux_net5.0:
          imageName: 'ubuntu-latest'
          targetFramework: 'net5.0'
          testArgs: '--filter Category!=WindowsOnly'
          additionalDotNetCoreSdk: '5.0.x'
        Linux_net6.0:
          imageName: 'ubuntu-latest'
          targetFramework: 'net6.0'
          testArgs: '--filter Category!=WindowsOnly'
          additionalDotNetCoreSdk: ''
    displayName: Test Debug
    pool:
      vmImage: $(imageName)
    steps:
    - task: DownloadPipelineArtifact@2
      displayName: Download build artifacts
      inputs:
        source: current
        artifact: DebugBuild
        path: $(System.DefaultWorkingDirectory)/bin

    - task: UseDotNet@2
      displayName: 'Use .NET Core 6 sdk'
      inputs:
        packageType: sdk
        version: '6.0.x'
        installationPath: $(Agent.ToolsDirectory)/dotnet

    - task: UseDotNet@2
      displayName: 'Use additional .NET Core sdk'
      inputs:
        packageType: sdk
        version: $(additionalDotNetCoreSdk)
        installationPath: $(Agent.ToolsDirectory)/dotnet
      condition: not(eq(variables.additionalDotNetCoreSdk, ''))

    - task: DotNetCoreCLI@2
      displayName: Restore packages
      inputs:
        command: 'build'
        projects: ${{ parameters.testProjects}}
        arguments: '--configuration Debug /t:restore'
        
    - task: DotNetCoreCLI@2
      displayName: Build test projects
      inputs:
        command: 'build'
        projects: ${{ parameters.testProjects}}
        arguments: '--configuration Debug --framework $(targetFramework)'

    - task: DotNetCoreCLI@2
      displayName: Run Tests
      timeoutInMinutes: 15
      inputs:
        command: 'test'
        projects: ${{ parameters.testProjects}}
        publishTestResults: true
        arguments: '--no-restore --no-build --configuration Debug --framework $(targetFramework) $(testArgs)'
