// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;

namespace CoreWCF.Http.Tests.Authorization;

public partial class AuthorizationIntegrationTests
{
    // simulate what is generated by OperationParameterInjectorGenerator
    public partial class SecuredService
    {
        [AuthorizeAttribute(Policy = Policies.Write)]
        public Task<string> Generated(string text)
        {
            _holder.IsGeneratedCalled = true;
            return Task.FromResult(text);
        }
    }
}