<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(TestTargetFrameworks)</TargetFrameworks>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="RabbitMQ.Client" />
    <PackageReference Include="Testcontainers" />
    <PackageReference Include="Testcontainers.RabbitMq" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="$(SourceDir)CoreWCF.RabbitMQ.Client\src\CoreWCF.RabbitMQ.Client.csproj" />
    <ProjectReference Include="..\src\CoreWCF.RabbitMQ.csproj" />
  </ItemGroup>

</Project>
