//HintName: App.MyContext.DataContractSerializers.g.cs
// <auto-generated>
// Generated by the CoreWCF.DataContractSerialization source generator. DO NOT EDIT!
// </auto-generated>
#nullable disable

namespace App
{
    partial class MyContext
    {
        /// <inheritdoc />
        public override global::CoreWCF.Runtime.Serialization.AotXmlObjectSerializer GetSerializer(global::System.Type type, global::System.Xml.XmlDictionaryString name, global::System.Xml.XmlDictionaryString ns)
        {
            // global::App.HasPrivateMember: member '_hidden' is not public
            if (type == typeof(global::App.NoDefaultConstructor))
            {
                return new __DataContractSerializer1(name, ns);
            }

            return null;
        }

        /// <inheritdoc />
        public override bool CoversKnownTypes(global::System.Type type, global::System.Collections.Generic.IList<global::System.Type> knownTypes)
        {
            if (knownTypes == null || knownTypes.Count == 0)
            {
                return true;
            }

            return false;
        }

        private static void WriteNil(global::System.Xml.XmlDictionaryWriter writer)
        {
            writer.WriteAttributeString("i", "nil", "http://www.w3.org/2001/XMLSchema-instance", "true");
        }

        private static void WriteDateTimeOffset(global::System.Xml.XmlDictionaryWriter writer, global::System.DateTimeOffset value)
        {
            writer.WriteStartElement("DateTime", "http://schemas.datacontract.org/2004/07/System");
            writer.WriteValue(value.UtcDateTime);
            writer.WriteEndElement();

            writer.WriteStartElement("OffsetMinutes", "http://schemas.datacontract.org/2004/07/System");
            writer.WriteValue((short)value.Offset.TotalMinutes);
            writer.WriteEndElement();
        }

        private static global::System.DateTimeOffset ReadDateTimeOffset(global::System.Xml.XmlDictionaryReader reader)
        {
            global::System.DateTime __dateTime = default;
            short __offsetMinutes = 0;

            if (reader.IsEmptyElement)
            {
                reader.Read();
            }
            else
            {
                reader.ReadStartElement();
                reader.MoveToContent();
                int __part = -1;
                while (reader.NodeType == global::System.Xml.XmlNodeType.Element)
                {
                    if (__part < 0
                        && reader.LocalName == "DateTime"
                        && reader.NamespaceURI == "http://schemas.datacontract.org/2004/07/System")
                    {
                        __dateTime = global::System.Xml.XmlConvert.ToDateTime(reader.ReadElementContentAsString(), global::System.Xml.XmlDateTimeSerializationMode.RoundtripKind);
                        __part = 0;
                    }
                    else if (__part < 1
                        && reader.LocalName == "OffsetMinutes"
                        && reader.NamespaceURI == "http://schemas.datacontract.org/2004/07/System")
                    {
                        __offsetMinutes = global::System.Xml.XmlConvert.ToInt16(reader.ReadElementContentAsString());
                        __part = 1;
                    }
                    else
                    {
                        reader.Skip();
                    }

                    reader.MoveToContent();
                }

                reader.ReadEndElement();
            }

            global::System.TimeSpan __offset = new global::System.TimeSpan(0, __offsetMinutes, 0);
            return __dateTime.Kind == global::System.DateTimeKind.Unspecified
                ? new global::System.DateTimeOffset(__dateTime, __offset)
                : new global::System.DateTimeOffset(__dateTime).ToOffset(__offset);
        }

        private static void WriteQName(global::System.Xml.XmlDictionaryWriter writer, global::System.Xml.XmlQualifiedName value)
        {
            if (value != global::System.Xml.XmlQualifiedName.Empty)
            {
                writer.WriteXmlnsAttribute(null, value.Namespace);
                writer.WriteQualifiedName(value.Name, value.Namespace);
            }
        }

        private static global::System.Xml.XmlQualifiedName ReadQName(global::System.Xml.XmlDictionaryReader reader)
        {
            if (reader.IsEmptyElement)
            {
                reader.Read();
                return global::System.Xml.XmlQualifiedName.Empty;
            }

            reader.ReadStartElement();
            string __text = reader.ReadContentAsString();
            global::System.Xml.XmlQualifiedName __name;

            if (__text.Length == 0)
            {
                __name = global::System.Xml.XmlQualifiedName.Empty;
            }
            else
            {
                int __colon = __text.IndexOf(':');
                string __prefix = __colon < 0 ? string.Empty : __text.Substring(0, __colon);
                string __namespace = reader.LookupNamespace(__prefix);

                if (__namespace == null)
                {
                    throw new global::System.Runtime.Serialization.SerializationException(
                        "Invalid qualified name '" + __text + "': the prefix is not declared.");
                }

                __name = new global::System.Xml.XmlQualifiedName(__text.Substring(__colon + 1), __namespace);
            }

            reader.ReadEndElement();
            return __name;
        }

        private static void ReadXsiType(global::System.Xml.XmlDictionaryReader reader, out string name, out string ns)
        {
            string __value = reader.GetAttribute("type", "http://www.w3.org/2001/XMLSchema-instance");

            if (__value == null)
            {
                name = null;
                ns = null;
                return;
            }

            int __colon = __value.IndexOf(':');
            string __prefix = __colon < 0 ? string.Empty : __value.Substring(0, __colon);
            ns = reader.LookupNamespace(__prefix);

            if (ns == null)
            {
                throw new global::System.Runtime.Serialization.SerializationException(
                    "Invalid i:type '" + __value + "': the prefix is not declared.");
            }

            name = __value.Substring(__colon + 1);
        }

        private static object ReadBoxedValue(global::System.Xml.XmlDictionaryReader reader, string name, string ns)
        {
            if (name == null)
            {
                // anyType: neither i:type nor content
                reader.Skip();
                return new object();
            }

            if (name == "boolean" && ns == "http://www.w3.org/2001/XMLSchema")
            {
                return global::System.Xml.XmlConvert.ToBoolean(reader.ReadElementContentAsString());
            }
            else if (name == "base64Binary" && ns == "http://www.w3.org/2001/XMLSchema")
            {
                return reader.ReadElementContentAsBase64();
            }
            else if (name == "char" && ns == "http://schemas.microsoft.com/2003/10/Serialization/")
            {
                return (char)global::System.Xml.XmlConvert.ToInt32(reader.ReadElementContentAsString());
            }
            else if (name == "dateTime" && ns == "http://www.w3.org/2001/XMLSchema")
            {
                return global::System.Xml.XmlConvert.ToDateTime(reader.ReadElementContentAsString(), global::System.Xml.XmlDateTimeSerializationMode.RoundtripKind);
            }
            else if (name == "decimal" && ns == "http://www.w3.org/2001/XMLSchema")
            {
                return global::System.Xml.XmlConvert.ToDecimal(reader.ReadElementContentAsString());
            }
            else if (name == "double" && ns == "http://www.w3.org/2001/XMLSchema")
            {
                return global::System.Xml.XmlConvert.ToDouble(reader.ReadElementContentAsString());
            }
            else if (name == "float" && ns == "http://www.w3.org/2001/XMLSchema")
            {
                return global::System.Xml.XmlConvert.ToSingle(reader.ReadElementContentAsString());
            }
            else if (name == "guid" && ns == "http://schemas.microsoft.com/2003/10/Serialization/")
            {
                return global::System.Xml.XmlConvert.ToGuid(reader.ReadElementContentAsString());
            }
            else if (name == "short" && ns == "http://www.w3.org/2001/XMLSchema")
            {
                return global::System.Xml.XmlConvert.ToInt16(reader.ReadElementContentAsString());
            }
            else if (name == "int" && ns == "http://www.w3.org/2001/XMLSchema")
            {
                return global::System.Xml.XmlConvert.ToInt32(reader.ReadElementContentAsString());
            }
            else if (name == "long" && ns == "http://www.w3.org/2001/XMLSchema")
            {
                return global::System.Xml.XmlConvert.ToInt64(reader.ReadElementContentAsString());
            }
            else if (name == "byte" && ns == "http://www.w3.org/2001/XMLSchema")
            {
                return global::System.Xml.XmlConvert.ToSByte(reader.ReadElementContentAsString());
            }
            else if (name == "string" && ns == "http://www.w3.org/2001/XMLSchema")
            {
                return reader.ReadElementContentAsString();
            }
            else if (name == "duration" && ns == "http://schemas.microsoft.com/2003/10/Serialization/")
            {
                return global::System.Xml.XmlConvert.ToTimeSpan(reader.ReadElementContentAsString());
            }
            else if (name == "anyURI" && ns == "http://www.w3.org/2001/XMLSchema")
            {
                return new global::System.Uri(reader.ReadElementContentAsString(), global::System.UriKind.RelativeOrAbsolute);
            }
            else if (name == "unsignedShort" && ns == "http://www.w3.org/2001/XMLSchema")
            {
                return global::System.Xml.XmlConvert.ToUInt16(reader.ReadElementContentAsString());
            }
            else if (name == "unsignedInt" && ns == "http://www.w3.org/2001/XMLSchema")
            {
                return global::System.Xml.XmlConvert.ToUInt32(reader.ReadElementContentAsString());
            }
            else if (name == "unsignedLong" && ns == "http://www.w3.org/2001/XMLSchema")
            {
                return global::System.Xml.XmlConvert.ToUInt64(reader.ReadElementContentAsString());
            }
            else if (name == "unsignedByte" && ns == "http://www.w3.org/2001/XMLSchema")
            {
                return global::System.Xml.XmlConvert.ToByte(reader.ReadElementContentAsString());
            }

            throw new global::System.Runtime.Serialization.SerializationException(
                "Element contains data from a type that maps to the name '" + ns + ":" + name +
                "'. The deserializer has no knowledge of any type that maps to this name.");
        }

        /// <summary>Reads one untyped item, the inverse of WriteAnyType.</summary>
        private static object ReadAnyType(global::System.Xml.XmlDictionaryReader reader)
        {
            if (IsNil(reader))
            {
                reader.Skip();
                return null;
            }

            ReadXsiType(reader, out string __itemName, out string __itemNamespace);
            return ReadBoxedValue(reader, __itemName, __itemNamespace);
        }

        /// <summary>Whether this runtime writes DateOnly and TimeOnly as primitives.</summary>
        private static readonly bool __DateOnlyIsPrimitive =
            global::System.Environment.Version.Major >= 10;

        private static void WriteDateOnly(global::System.Xml.XmlDictionaryWriter writer, global::System.DateOnly value)
        {
            if (__DateOnlyIsPrimitive)
            {
                writer.WriteString(value.ToString("yyyy-MM-dd", global::System.Globalization.CultureInfo.InvariantCulture));
            }
        }

        private static void WriteTimeOnly(global::System.Xml.XmlDictionaryWriter writer, global::System.TimeOnly value)
        {
            if (__DateOnlyIsPrimitive)
            {
                writer.WriteString(value.ToString("HH:mm:ss.FFFFFFF", global::System.Globalization.CultureInfo.InvariantCulture));
            }
        }

        private static global::System.DateOnly ReadDateOnly(string text)
        {
            if (!__DateOnlyIsPrimitive)
            {
                return default;
            }

            return global::System.DateOnly.ParseExact(
                text,
                "yyyy-MM-dd",
                global::System.Globalization.DateTimeFormatInfo.InvariantInfo,
                global::System.Globalization.DateTimeStyles.AllowLeadingWhite | global::System.Globalization.DateTimeStyles.AllowTrailingWhite);
        }

        private static global::System.TimeOnly ReadTimeOnly(string text)
        {
            if (!__DateOnlyIsPrimitive)
            {
                return default;
            }

            return global::System.TimeOnly.FromTimeSpan(
                global::System.Xml.XmlConvert.ToDateTimeOffset(text).TimeOfDay);
        }

        private static bool IsNil(global::System.Xml.XmlDictionaryReader reader) =>
            reader.GetAttribute("nil", "http://www.w3.org/2001/XMLSchema-instance") == "true";

        /// <summary>Reads an element's text, or null when it carries i:nil.</summary>
        private static string ReadText(global::System.Xml.XmlDictionaryReader reader)
        {
            if (IsNil(reader))
            {
                reader.Skip();
                return null;
            }

            return reader.ReadElementContentAsString();
        }

        private static void WriteAnyType(global::System.Xml.XmlDictionaryWriter writer, object value)
        {
            if (value == null)
            {
                WriteNil(writer);
                return;
            }

            global::System.Type __runtimeType = value.GetType();
            if (__runtimeType == typeof(object))
            {
                // anyType: neither i:type nor content
            }
            else if (__runtimeType == typeof(bool))
            {
                writer.WriteXmlnsAttribute(null, "http://www.w3.org/2001/XMLSchema");
                writer.WriteStartAttribute("i", "type", "http://www.w3.org/2001/XMLSchema-instance");
                writer.WriteQualifiedName("boolean", "http://www.w3.org/2001/XMLSchema");
                writer.WriteEndAttribute();
                writer.WriteValue(((bool)value));
            }
            else if (__runtimeType == typeof(byte[]))
            {
                writer.WriteXmlnsAttribute(null, "http://www.w3.org/2001/XMLSchema");
                writer.WriteStartAttribute("i", "type", "http://www.w3.org/2001/XMLSchema-instance");
                writer.WriteQualifiedName("base64Binary", "http://www.w3.org/2001/XMLSchema");
                writer.WriteEndAttribute();
                writer.WriteBase64(((byte[])value), 0, ((byte[])value).Length);
            }
            else if (__runtimeType == typeof(char))
            {
                writer.WriteXmlnsAttribute(null, "http://schemas.microsoft.com/2003/10/Serialization/");
                writer.WriteStartAttribute("i", "type", "http://www.w3.org/2001/XMLSchema-instance");
                writer.WriteQualifiedName("char", "http://schemas.microsoft.com/2003/10/Serialization/");
                writer.WriteEndAttribute();
                writer.WriteValue((int)((char)value));
            }
            else if (__runtimeType == typeof(global::System.DateTime))
            {
                writer.WriteXmlnsAttribute(null, "http://www.w3.org/2001/XMLSchema");
                writer.WriteStartAttribute("i", "type", "http://www.w3.org/2001/XMLSchema-instance");
                writer.WriteQualifiedName("dateTime", "http://www.w3.org/2001/XMLSchema");
                writer.WriteEndAttribute();
                writer.WriteValue(((global::System.DateTime)value));
            }
            else if (__runtimeType == typeof(decimal))
            {
                writer.WriteXmlnsAttribute(null, "http://www.w3.org/2001/XMLSchema");
                writer.WriteStartAttribute("i", "type", "http://www.w3.org/2001/XMLSchema-instance");
                writer.WriteQualifiedName("decimal", "http://www.w3.org/2001/XMLSchema");
                writer.WriteEndAttribute();
                writer.WriteValue(((decimal)value));
            }
            else if (__runtimeType == typeof(double))
            {
                writer.WriteXmlnsAttribute(null, "http://www.w3.org/2001/XMLSchema");
                writer.WriteStartAttribute("i", "type", "http://www.w3.org/2001/XMLSchema-instance");
                writer.WriteQualifiedName("double", "http://www.w3.org/2001/XMLSchema");
                writer.WriteEndAttribute();
                writer.WriteValue(((double)value));
            }
            else if (__runtimeType == typeof(float))
            {
                writer.WriteXmlnsAttribute(null, "http://www.w3.org/2001/XMLSchema");
                writer.WriteStartAttribute("i", "type", "http://www.w3.org/2001/XMLSchema-instance");
                writer.WriteQualifiedName("float", "http://www.w3.org/2001/XMLSchema");
                writer.WriteEndAttribute();
                writer.WriteValue(((float)value));
            }
            else if (__runtimeType == typeof(global::System.Guid))
            {
                writer.WriteXmlnsAttribute(null, "http://schemas.microsoft.com/2003/10/Serialization/");
                writer.WriteStartAttribute("i", "type", "http://www.w3.org/2001/XMLSchema-instance");
                writer.WriteQualifiedName("guid", "http://schemas.microsoft.com/2003/10/Serialization/");
                writer.WriteEndAttribute();
                writer.WriteRaw(((global::System.Guid)value).ToString());
            }
            else if (__runtimeType == typeof(short))
            {
                writer.WriteXmlnsAttribute(null, "http://www.w3.org/2001/XMLSchema");
                writer.WriteStartAttribute("i", "type", "http://www.w3.org/2001/XMLSchema-instance");
                writer.WriteQualifiedName("short", "http://www.w3.org/2001/XMLSchema");
                writer.WriteEndAttribute();
                writer.WriteValue(((short)value));
            }
            else if (__runtimeType == typeof(int))
            {
                writer.WriteXmlnsAttribute(null, "http://www.w3.org/2001/XMLSchema");
                writer.WriteStartAttribute("i", "type", "http://www.w3.org/2001/XMLSchema-instance");
                writer.WriteQualifiedName("int", "http://www.w3.org/2001/XMLSchema");
                writer.WriteEndAttribute();
                writer.WriteValue(((int)value));
            }
            else if (__runtimeType == typeof(long))
            {
                writer.WriteXmlnsAttribute(null, "http://www.w3.org/2001/XMLSchema");
                writer.WriteStartAttribute("i", "type", "http://www.w3.org/2001/XMLSchema-instance");
                writer.WriteQualifiedName("long", "http://www.w3.org/2001/XMLSchema");
                writer.WriteEndAttribute();
                writer.WriteValue(((long)value));
            }
            else if (__runtimeType == typeof(sbyte))
            {
                writer.WriteXmlnsAttribute(null, "http://www.w3.org/2001/XMLSchema");
                writer.WriteStartAttribute("i", "type", "http://www.w3.org/2001/XMLSchema-instance");
                writer.WriteQualifiedName("byte", "http://www.w3.org/2001/XMLSchema");
                writer.WriteEndAttribute();
                writer.WriteValue(((sbyte)value));
            }
            else if (__runtimeType == typeof(string))
            {
                writer.WriteXmlnsAttribute(null, "http://www.w3.org/2001/XMLSchema");
                writer.WriteStartAttribute("i", "type", "http://www.w3.org/2001/XMLSchema-instance");
                writer.WriteQualifiedName("string", "http://www.w3.org/2001/XMLSchema");
                writer.WriteEndAttribute();
                writer.WriteValue(((string)value));
            }
            else if (__runtimeType == typeof(global::System.TimeSpan))
            {
                writer.WriteXmlnsAttribute(null, "http://schemas.microsoft.com/2003/10/Serialization/");
                writer.WriteStartAttribute("i", "type", "http://www.w3.org/2001/XMLSchema-instance");
                writer.WriteQualifiedName("duration", "http://schemas.microsoft.com/2003/10/Serialization/");
                writer.WriteEndAttribute();
                writer.WriteRaw(global::System.Xml.XmlConvert.ToString(((global::System.TimeSpan)value)));
            }
            else if (__runtimeType == typeof(global::System.Uri))
            {
                writer.WriteXmlnsAttribute(null, "http://www.w3.org/2001/XMLSchema");
                writer.WriteStartAttribute("i", "type", "http://www.w3.org/2001/XMLSchema-instance");
                writer.WriteQualifiedName("anyURI", "http://www.w3.org/2001/XMLSchema");
                writer.WriteEndAttribute();
                writer.WriteString(((global::System.Uri)value).GetComponents(global::System.UriComponents.SerializationInfoString, global::System.UriFormat.UriEscaped));
            }
            else if (__runtimeType == typeof(ushort))
            {
                writer.WriteXmlnsAttribute(null, "http://www.w3.org/2001/XMLSchema");
                writer.WriteStartAttribute("i", "type", "http://www.w3.org/2001/XMLSchema-instance");
                writer.WriteQualifiedName("unsignedShort", "http://www.w3.org/2001/XMLSchema");
                writer.WriteEndAttribute();
                writer.WriteValue(((ushort)value));
            }
            else if (__runtimeType == typeof(uint))
            {
                writer.WriteXmlnsAttribute(null, "http://www.w3.org/2001/XMLSchema");
                writer.WriteStartAttribute("i", "type", "http://www.w3.org/2001/XMLSchema-instance");
                writer.WriteQualifiedName("unsignedInt", "http://www.w3.org/2001/XMLSchema");
                writer.WriteEndAttribute();
                writer.WriteValue(((uint)value));
            }
            else if (__runtimeType == typeof(ulong))
            {
                writer.WriteXmlnsAttribute(null, "http://www.w3.org/2001/XMLSchema");
                writer.WriteStartAttribute("i", "type", "http://www.w3.org/2001/XMLSchema-instance");
                writer.WriteQualifiedName("unsignedLong", "http://www.w3.org/2001/XMLSchema");
                writer.WriteEndAttribute();
                writer.WriteRaw(global::System.Xml.XmlConvert.ToString(((ulong)value)));
            }
            else if (__runtimeType == typeof(byte))
            {
                writer.WriteXmlnsAttribute(null, "http://www.w3.org/2001/XMLSchema");
                writer.WriteStartAttribute("i", "type", "http://www.w3.org/2001/XMLSchema-instance");
                writer.WriteQualifiedName("unsignedByte", "http://www.w3.org/2001/XMLSchema");
                writer.WriteEndAttribute();
                writer.WriteValue(((byte)value));
            }
            else
            {
                throw new global::System.Runtime.Serialization.SerializationException(
                    "Type '" + __runtimeType.FullName + "' cannot be written as an untyped array item.");
            }
        }

        private sealed class __ReferenceScope
        {
            private global::System.Collections.Generic.Dictionary<object, int> _ids;
            private global::System.Collections.Generic.HashSet<object> _byValueInScope;
            private int _next = 1;
            private int _depth;

            /// <summary>Depth past which a by-value graph starts being checked for cycles.</summary>
            private const int DepthToCheckCyclicReference = 512;

            /// <summary>Enters a contract written by value, throwing if it is already on the path.</summary>
            internal void EnterByValue(object value)
            {
                if (++_depth < DepthToCheckCyclicReference)
                {
                    return;
                }

                if (_byValueInScope == null)
                {
                    _byValueInScope = new global::System.Collections.Generic.HashSet<object>(
                        global::System.Collections.Generic.ReferenceEqualityComparer.Instance);
                }

                if (!_byValueInScope.Add(value))
                {
                    throw new global::System.Runtime.Serialization.SerializationException(
                        "Object graph for type '" + value.GetType().FullName + "' contains cycles and cannot be " +
                        "serialized if references are not tracked. Consider using the DataContractAttribute " +
                        "with the IsReference property set to true.");
                }
            }

            internal void ExitByValue(object value)
            {
                if (_depth >= DepthToCheckCyclicReference && _byValueInScope != null)
                {
                    _byValueInScope.Remove(value);
                }

                _depth--;
            }

            /// <summary>Returns true when z:Ref was written, meaning the content must not be repeated.</summary>
            internal bool WriteIdOrRef(global::System.Xml.XmlDictionaryWriter writer, object value)
            {
                if (_ids == null)
                {
                    _ids = new global::System.Collections.Generic.Dictionary<object, int>(
                        global::System.Collections.Generic.ReferenceEqualityComparer.Instance);
                }

                int id;
                if (_ids.TryGetValue(value, out id))
                {
                    writer.WriteAttributeString("z", "Ref", "http://schemas.microsoft.com/2003/10/Serialization/", Id(id));
                    return true;
                }

                id = _next++;
                _ids.Add(value, id);
                writer.WriteAttributeString("z", "Id", "http://schemas.microsoft.com/2003/10/Serialization/", Id(id));
                return false;
            }

            private static string Id(int id) =>
                "i" + id.ToString(global::System.Globalization.CultureInfo.InvariantCulture);
        }

        private sealed class __ReadScope
        {
            private global::System.Collections.Generic.Dictionary<string, object> _byId;

            /// <summary>Records an instance under its z:Id, before any of its members are read.</summary>
            /// <remarks>
            /// Before, not after. An instance inside its own graph is referred to while it is still
            /// being filled in - which is what a cycle is - so recording it late would turn a z:Ref
            /// into a lookup that fails. Mirrors AddNewObject, which upstream calls before
            /// deserializing members for the same reason.
            /// </remarks>
            internal void Add(string id, object value)
            {
                if (id == null)
                {
                    return;
                }

                if (_byId == null)
                {
                    _byId = new global::System.Collections.Generic.Dictionary<string, object>(
                        global::System.StringComparer.Ordinal);
                }

                _byId[id] = value;
            }

            internal object Get(string id)
            {
                if (_byId != null && _byId.TryGetValue(id, out object value))
                {
                    return value;
                }

                throw new global::System.Runtime.Serialization.SerializationException(
                    "Deserialized object with reference id '" + id + "' not found.");
            }
        }

        /// <summary>Writes the members of NoDefaultConstructor, without a wrapping element.</summary>
        private static void __WriteContent1(global::System.Xml.XmlDictionaryWriter writer, global::App.NoDefaultConstructor value, __ReferenceScope scope)
        {
            // Value (Order = -1)
            writer.WriteStartElement("Value", "http://schemas.datacontract.org/2004/07/App");
            writer.WriteValue(value.Value);
            writer.WriteEndElement();
        }

        /// <summary>Writes NoDefaultConstructor in http://schemas.datacontract.org/2004/07/App.</summary>
        private sealed class __DataContractSerializer1 : global::CoreWCF.Runtime.Serialization.AotXmlObjectSerializer
        {
            private readonly global::System.Xml.XmlDictionaryString _name;
            private readonly global::System.Xml.XmlDictionaryString _ns;

            internal __DataContractSerializer1(global::System.Xml.XmlDictionaryString name, global::System.Xml.XmlDictionaryString ns)
            {
                _name = name;
                _ns = ns;
            }

            /// <inheritdoc />
            public override void WriteObject(global::System.Xml.XmlDictionaryWriter writer, object graph)
            {
                writer.WriteStartElement(_name, _ns);

                if (!string.Equals("http://schemas.datacontract.org/2004/07/App", _ns?.Value, global::System.StringComparison.Ordinal))
                {
                    writer.WriteXmlnsAttribute(null, "http://schemas.datacontract.org/2004/07/App");
                }

                writer.WriteXmlnsAttribute("i", "http://www.w3.org/2001/XMLSchema-instance");

                if (graph == null)
                {
                    WriteNil(writer);
                }
                else
                {
                    __ReferenceScope scope = new __ReferenceScope();
                    __WriteContent1(writer, (global::App.NoDefaultConstructor)graph, scope);
                }

                writer.WriteEndElement();
            }
        }
    }
}

#nullable restore
