//HintName: App.MyContext.DataContractSerializers.g.cs
// <auto-generated>
// Generated by the CoreWCF.DataContractSerialization source generator. DO NOT EDIT!
// </auto-generated>
#nullable disable

namespace App
{
    partial class MyContext
    {
        /// <inheritdoc />
        public override global::CoreWCF.Runtime.Serialization.AotXmlObjectSerializer GetSerializer(global::System.Type type, global::System.Xml.XmlDictionaryString name, global::System.Xml.XmlDictionaryString ns)
        {
            if (type == typeof(global::App.Bag))
            {
                return new __DataContractSerializer0(name, ns);
            }

            return null;
        }

        /// <inheritdoc />
        public override bool CoversKnownTypes(global::System.Type type, global::System.Collections.Generic.IList<global::System.Type> knownTypes)
        {
            if (knownTypes == null || knownTypes.Count == 0)
            {
                return true;
            }

            return false;
        }

        private static void WriteNil(global::System.Xml.XmlDictionaryWriter writer)
        {
            writer.WriteAttributeString("i", "nil", "http://www.w3.org/2001/XMLSchema-instance", "true");
        }

        private static void WriteDateTimeOffset(global::System.Xml.XmlDictionaryWriter writer, global::System.DateTimeOffset value)
        {
            writer.WriteStartElement("DateTime", "http://schemas.datacontract.org/2004/07/System");
            writer.WriteValue(value.UtcDateTime);
            writer.WriteEndElement();

            writer.WriteStartElement("OffsetMinutes", "http://schemas.datacontract.org/2004/07/System");
            writer.WriteValue((short)value.Offset.TotalMinutes);
            writer.WriteEndElement();
        }

        private static global::System.DateTimeOffset ReadDateTimeOffset(global::System.Xml.XmlDictionaryReader reader)
        {
            global::System.DateTime __dateTime = default;
            short __offsetMinutes = 0;

            if (reader.IsEmptyElement)
            {
                reader.Read();
            }
            else
            {
                reader.ReadStartElement();
                reader.MoveToContent();
                int __part = -1;
                while (reader.NodeType == global::System.Xml.XmlNodeType.Element)
                {
                    if (__part < 0
                        && reader.LocalName == "DateTime"
                        && reader.NamespaceURI == "http://schemas.datacontract.org/2004/07/System")
                    {
                        __dateTime = global::System.Xml.XmlConvert.ToDateTime(reader.ReadElementContentAsString(), global::System.Xml.XmlDateTimeSerializationMode.RoundtripKind);
                        __part = 0;
                    }
                    else if (__part < 1
                        && reader.LocalName == "OffsetMinutes"
                        && reader.NamespaceURI == "http://schemas.datacontract.org/2004/07/System")
                    {
                        __offsetMinutes = global::System.Xml.XmlConvert.ToInt16(reader.ReadElementContentAsString());
                        __part = 1;
                    }
                    else
                    {
                        reader.Skip();
                    }

                    reader.MoveToContent();
                }

                reader.ReadEndElement();
            }

            global::System.TimeSpan __offset = new global::System.TimeSpan(0, __offsetMinutes, 0);
            return __dateTime.Kind == global::System.DateTimeKind.Unspecified
                ? new global::System.DateTimeOffset(__dateTime, __offset)
                : new global::System.DateTimeOffset(__dateTime).ToOffset(__offset);
        }

        private static void WriteQName(global::System.Xml.XmlDictionaryWriter writer, global::System.Xml.XmlQualifiedName value)
        {
            if (value != global::System.Xml.XmlQualifiedName.Empty)
            {
                writer.WriteXmlnsAttribute(null, value.Namespace);
                writer.WriteQualifiedName(value.Name, value.Namespace);
            }
        }

        private static global::System.Xml.XmlQualifiedName ReadQName(global::System.Xml.XmlDictionaryReader reader)
        {
            if (reader.IsEmptyElement)
            {
                reader.Read();
                return global::System.Xml.XmlQualifiedName.Empty;
            }

            reader.ReadStartElement();
            string __text = reader.ReadContentAsString();
            global::System.Xml.XmlQualifiedName __name;

            if (__text.Length == 0)
            {
                __name = global::System.Xml.XmlQualifiedName.Empty;
            }
            else
            {
                int __colon = __text.IndexOf(':');
                string __prefix = __colon < 0 ? string.Empty : __text.Substring(0, __colon);
                string __namespace = reader.LookupNamespace(__prefix);

                if (__namespace == null)
                {
                    throw new global::System.Runtime.Serialization.SerializationException(
                        "Invalid qualified name '" + __text + "': the prefix is not declared.");
                }

                __name = new global::System.Xml.XmlQualifiedName(__text.Substring(__colon + 1), __namespace);
            }

            reader.ReadEndElement();
            return __name;
        }

        private static void ReadXsiType(global::System.Xml.XmlDictionaryReader reader, out string name, out string ns)
        {
            string __value = reader.GetAttribute("type", "http://www.w3.org/2001/XMLSchema-instance");

            if (__value == null)
            {
                name = null;
                ns = null;
                return;
            }

            int __colon = __value.IndexOf(':');
            string __prefix = __colon < 0 ? string.Empty : __value.Substring(0, __colon);
            ns = reader.LookupNamespace(__prefix);

            if (ns == null)
            {
                throw new global::System.Runtime.Serialization.SerializationException(
                    "Invalid i:type '" + __value + "': the prefix is not declared.");
            }

            name = __value.Substring(__colon + 1);
        }

        private static object ReadBoxedValue(global::System.Xml.XmlDictionaryReader reader, string name, string ns)
        {
            if (name == null)
            {
                // anyType: neither i:type nor content
                reader.Skip();
                return new object();
            }

            if (name == "boolean" && ns == "http://www.w3.org/2001/XMLSchema")
            {
                return global::System.Xml.XmlConvert.ToBoolean(reader.ReadElementContentAsString());
            }
            else if (name == "base64Binary" && ns == "http://www.w3.org/2001/XMLSchema")
            {
                return reader.ReadElementContentAsBase64();
            }
            else if (name == "char" && ns == "http://schemas.microsoft.com/2003/10/Serialization/")
            {
                return (char)global::System.Xml.XmlConvert.ToInt32(reader.ReadElementContentAsString());
            }
            else if (name == "dateTime" && ns == "http://www.w3.org/2001/XMLSchema")
            {
                return global::System.Xml.XmlConvert.ToDateTime(reader.ReadElementContentAsString(), global::System.Xml.XmlDateTimeSerializationMode.RoundtripKind);
            }
            else if (name == "decimal" && ns == "http://www.w3.org/2001/XMLSchema")
            {
                return global::System.Xml.XmlConvert.ToDecimal(reader.ReadElementContentAsString());
            }
            else if (name == "double" && ns == "http://www.w3.org/2001/XMLSchema")
            {
                return global::System.Xml.XmlConvert.ToDouble(reader.ReadElementContentAsString());
            }
            else if (name == "float" && ns == "http://www.w3.org/2001/XMLSchema")
            {
                return global::System.Xml.XmlConvert.ToSingle(reader.ReadElementContentAsString());
            }
            else if (name == "guid" && ns == "http://schemas.microsoft.com/2003/10/Serialization/")
            {
                return global::System.Xml.XmlConvert.ToGuid(reader.ReadElementContentAsString());
            }
            else if (name == "short" && ns == "http://www.w3.org/2001/XMLSchema")
            {
                return global::System.Xml.XmlConvert.ToInt16(reader.ReadElementContentAsString());
            }
            else if (name == "int" && ns == "http://www.w3.org/2001/XMLSchema")
            {
                return global::System.Xml.XmlConvert.ToInt32(reader.ReadElementContentAsString());
            }
            else if (name == "long" && ns == "http://www.w3.org/2001/XMLSchema")
            {
                return global::System.Xml.XmlConvert.ToInt64(reader.ReadElementContentAsString());
            }
            else if (name == "byte" && ns == "http://www.w3.org/2001/XMLSchema")
            {
                return global::System.Xml.XmlConvert.ToSByte(reader.ReadElementContentAsString());
            }
            else if (name == "string" && ns == "http://www.w3.org/2001/XMLSchema")
            {
                return reader.ReadElementContentAsString();
            }
            else if (name == "duration" && ns == "http://schemas.microsoft.com/2003/10/Serialization/")
            {
                return global::System.Xml.XmlConvert.ToTimeSpan(reader.ReadElementContentAsString());
            }
            else if (name == "anyURI" && ns == "http://www.w3.org/2001/XMLSchema")
            {
                return new global::System.Uri(reader.ReadElementContentAsString(), global::System.UriKind.RelativeOrAbsolute);
            }
            else if (name == "unsignedShort" && ns == "http://www.w3.org/2001/XMLSchema")
            {
                return global::System.Xml.XmlConvert.ToUInt16(reader.ReadElementContentAsString());
            }
            else if (name == "unsignedInt" && ns == "http://www.w3.org/2001/XMLSchema")
            {
                return global::System.Xml.XmlConvert.ToUInt32(reader.ReadElementContentAsString());
            }
            else if (name == "unsignedLong" && ns == "http://www.w3.org/2001/XMLSchema")
            {
                return global::System.Xml.XmlConvert.ToUInt64(reader.ReadElementContentAsString());
            }
            else if (name == "unsignedByte" && ns == "http://www.w3.org/2001/XMLSchema")
            {
                return global::System.Xml.XmlConvert.ToByte(reader.ReadElementContentAsString());
            }

            throw new global::System.Runtime.Serialization.SerializationException(
                "Element contains data from a type that maps to the name '" + ns + ":" + name +
                "'. The deserializer has no knowledge of any type that maps to this name.");
        }

        /// <summary>Reads one untyped item, the inverse of WriteAnyType.</summary>
        private static object ReadAnyType(global::System.Xml.XmlDictionaryReader reader)
        {
            if (IsNil(reader))
            {
                reader.Skip();
                return null;
            }

            ReadXsiType(reader, out string __itemName, out string __itemNamespace);
            return ReadBoxedValue(reader, __itemName, __itemNamespace);
        }

        /// <summary>Whether this runtime writes DateOnly and TimeOnly as primitives.</summary>
        private static readonly bool __DateOnlyIsPrimitive =
            global::System.Environment.Version.Major >= 10;

        private static void WriteDateOnly(global::System.Xml.XmlDictionaryWriter writer, global::System.DateOnly value)
        {
            if (__DateOnlyIsPrimitive)
            {
                writer.WriteString(value.ToString("yyyy-MM-dd", global::System.Globalization.CultureInfo.InvariantCulture));
            }
        }

        private static void WriteTimeOnly(global::System.Xml.XmlDictionaryWriter writer, global::System.TimeOnly value)
        {
            if (__DateOnlyIsPrimitive)
            {
                writer.WriteString(value.ToString("HH:mm:ss.FFFFFFF", global::System.Globalization.CultureInfo.InvariantCulture));
            }
        }

        private static global::System.DateOnly ReadDateOnly(string text)
        {
            if (!__DateOnlyIsPrimitive)
            {
                return default;
            }

            return global::System.DateOnly.ParseExact(
                text,
                "yyyy-MM-dd",
                global::System.Globalization.DateTimeFormatInfo.InvariantInfo,
                global::System.Globalization.DateTimeStyles.AllowLeadingWhite | global::System.Globalization.DateTimeStyles.AllowTrailingWhite);
        }

        private static global::System.TimeOnly ReadTimeOnly(string text)
        {
            if (!__DateOnlyIsPrimitive)
            {
                return default;
            }

            return global::System.TimeOnly.FromTimeSpan(
                global::System.Xml.XmlConvert.ToDateTimeOffset(text).TimeOfDay);
        }

        private static bool IsNil(global::System.Xml.XmlDictionaryReader reader) =>
            reader.GetAttribute("nil", "http://www.w3.org/2001/XMLSchema-instance") == "true";

        /// <summary>Reads an element's text, or null when it carries i:nil.</summary>
        private static string ReadText(global::System.Xml.XmlDictionaryReader reader)
        {
            if (IsNil(reader))
            {
                reader.Skip();
                return null;
            }

            return reader.ReadElementContentAsString();
        }

        private static void WriteAnyType(global::System.Xml.XmlDictionaryWriter writer, object value)
        {
            if (value == null)
            {
                WriteNil(writer);
                return;
            }

            global::System.Type __runtimeType = value.GetType();
            if (__runtimeType == typeof(object))
            {
                // anyType: neither i:type nor content
            }
            else if (__runtimeType == typeof(bool))
            {
                writer.WriteXmlnsAttribute(null, "http://www.w3.org/2001/XMLSchema");
                writer.WriteStartAttribute("i", "type", "http://www.w3.org/2001/XMLSchema-instance");
                writer.WriteQualifiedName("boolean", "http://www.w3.org/2001/XMLSchema");
                writer.WriteEndAttribute();
                writer.WriteValue(((bool)value));
            }
            else if (__runtimeType == typeof(byte[]))
            {
                writer.WriteXmlnsAttribute(null, "http://www.w3.org/2001/XMLSchema");
                writer.WriteStartAttribute("i", "type", "http://www.w3.org/2001/XMLSchema-instance");
                writer.WriteQualifiedName("base64Binary", "http://www.w3.org/2001/XMLSchema");
                writer.WriteEndAttribute();
                writer.WriteBase64(((byte[])value), 0, ((byte[])value).Length);
            }
            else if (__runtimeType == typeof(char))
            {
                writer.WriteXmlnsAttribute(null, "http://schemas.microsoft.com/2003/10/Serialization/");
                writer.WriteStartAttribute("i", "type", "http://www.w3.org/2001/XMLSchema-instance");
                writer.WriteQualifiedName("char", "http://schemas.microsoft.com/2003/10/Serialization/");
                writer.WriteEndAttribute();
                writer.WriteValue((int)((char)value));
            }
            else if (__runtimeType == typeof(global::System.DateTime))
            {
                writer.WriteXmlnsAttribute(null, "http://www.w3.org/2001/XMLSchema");
                writer.WriteStartAttribute("i", "type", "http://www.w3.org/2001/XMLSchema-instance");
                writer.WriteQualifiedName("dateTime", "http://www.w3.org/2001/XMLSchema");
                writer.WriteEndAttribute();
                writer.WriteValue(((global::System.DateTime)value));
            }
            else if (__runtimeType == typeof(decimal))
            {
                writer.WriteXmlnsAttribute(null, "http://www.w3.org/2001/XMLSchema");
                writer.WriteStartAttribute("i", "type", "http://www.w3.org/2001/XMLSchema-instance");
                writer.WriteQualifiedName("decimal", "http://www.w3.org/2001/XMLSchema");
                writer.WriteEndAttribute();
                writer.WriteValue(((decimal)value));
            }
            else if (__runtimeType == typeof(double))
            {
                writer.WriteXmlnsAttribute(null, "http://www.w3.org/2001/XMLSchema");
                writer.WriteStartAttribute("i", "type", "http://www.w3.org/2001/XMLSchema-instance");
                writer.WriteQualifiedName("double", "http://www.w3.org/2001/XMLSchema");
                writer.WriteEndAttribute();
                writer.WriteValue(((double)value));
            }
            else if (__runtimeType == typeof(float))
            {
                writer.WriteXmlnsAttribute(null, "http://www.w3.org/2001/XMLSchema");
                writer.WriteStartAttribute("i", "type", "http://www.w3.org/2001/XMLSchema-instance");
                writer.WriteQualifiedName("float", "http://www.w3.org/2001/XMLSchema");
                writer.WriteEndAttribute();
                writer.WriteValue(((float)value));
            }
            else if (__runtimeType == typeof(global::System.Guid))
            {
                writer.WriteXmlnsAttribute(null, "http://schemas.microsoft.com/2003/10/Serialization/");
                writer.WriteStartAttribute("i", "type", "http://www.w3.org/2001/XMLSchema-instance");
                writer.WriteQualifiedName("guid", "http://schemas.microsoft.com/2003/10/Serialization/");
                writer.WriteEndAttribute();
                writer.WriteRaw(((global::System.Guid)value).ToString());
            }
            else if (__runtimeType == typeof(short))
            {
                writer.WriteXmlnsAttribute(null, "http://www.w3.org/2001/XMLSchema");
                writer.WriteStartAttribute("i", "type", "http://www.w3.org/2001/XMLSchema-instance");
                writer.WriteQualifiedName("short", "http://www.w3.org/2001/XMLSchema");
                writer.WriteEndAttribute();
                writer.WriteValue(((short)value));
            }
            else if (__runtimeType == typeof(int))
            {
                writer.WriteXmlnsAttribute(null, "http://www.w3.org/2001/XMLSchema");
                writer.WriteStartAttribute("i", "type", "http://www.w3.org/2001/XMLSchema-instance");
                writer.WriteQualifiedName("int", "http://www.w3.org/2001/XMLSchema");
                writer.WriteEndAttribute();
                writer.WriteValue(((int)value));
            }
            else if (__runtimeType == typeof(long))
            {
                writer.WriteXmlnsAttribute(null, "http://www.w3.org/2001/XMLSchema");
                writer.WriteStartAttribute("i", "type", "http://www.w3.org/2001/XMLSchema-instance");
                writer.WriteQualifiedName("long", "http://www.w3.org/2001/XMLSchema");
                writer.WriteEndAttribute();
                writer.WriteValue(((long)value));
            }
            else if (__runtimeType == typeof(sbyte))
            {
                writer.WriteXmlnsAttribute(null, "http://www.w3.org/2001/XMLSchema");
                writer.WriteStartAttribute("i", "type", "http://www.w3.org/2001/XMLSchema-instance");
                writer.WriteQualifiedName("byte", "http://www.w3.org/2001/XMLSchema");
                writer.WriteEndAttribute();
                writer.WriteValue(((sbyte)value));
            }
            else if (__runtimeType == typeof(string))
            {
                writer.WriteXmlnsAttribute(null, "http://www.w3.org/2001/XMLSchema");
                writer.WriteStartAttribute("i", "type", "http://www.w3.org/2001/XMLSchema-instance");
                writer.WriteQualifiedName("string", "http://www.w3.org/2001/XMLSchema");
                writer.WriteEndAttribute();
                writer.WriteValue(((string)value));
            }
            else if (__runtimeType == typeof(global::System.TimeSpan))
            {
                writer.WriteXmlnsAttribute(null, "http://schemas.microsoft.com/2003/10/Serialization/");
                writer.WriteStartAttribute("i", "type", "http://www.w3.org/2001/XMLSchema-instance");
                writer.WriteQualifiedName("duration", "http://schemas.microsoft.com/2003/10/Serialization/");
                writer.WriteEndAttribute();
                writer.WriteRaw(global::System.Xml.XmlConvert.ToString(((global::System.TimeSpan)value)));
            }
            else if (__runtimeType == typeof(global::System.Uri))
            {
                writer.WriteXmlnsAttribute(null, "http://www.w3.org/2001/XMLSchema");
                writer.WriteStartAttribute("i", "type", "http://www.w3.org/2001/XMLSchema-instance");
                writer.WriteQualifiedName("anyURI", "http://www.w3.org/2001/XMLSchema");
                writer.WriteEndAttribute();
                writer.WriteString(((global::System.Uri)value).GetComponents(global::System.UriComponents.SerializationInfoString, global::System.UriFormat.UriEscaped));
            }
            else if (__runtimeType == typeof(ushort))
            {
                writer.WriteXmlnsAttribute(null, "http://www.w3.org/2001/XMLSchema");
                writer.WriteStartAttribute("i", "type", "http://www.w3.org/2001/XMLSchema-instance");
                writer.WriteQualifiedName("unsignedShort", "http://www.w3.org/2001/XMLSchema");
                writer.WriteEndAttribute();
                writer.WriteValue(((ushort)value));
            }
            else if (__runtimeType == typeof(uint))
            {
                writer.WriteXmlnsAttribute(null, "http://www.w3.org/2001/XMLSchema");
                writer.WriteStartAttribute("i", "type", "http://www.w3.org/2001/XMLSchema-instance");
                writer.WriteQualifiedName("unsignedInt", "http://www.w3.org/2001/XMLSchema");
                writer.WriteEndAttribute();
                writer.WriteValue(((uint)value));
            }
            else if (__runtimeType == typeof(ulong))
            {
                writer.WriteXmlnsAttribute(null, "http://www.w3.org/2001/XMLSchema");
                writer.WriteStartAttribute("i", "type", "http://www.w3.org/2001/XMLSchema-instance");
                writer.WriteQualifiedName("unsignedLong", "http://www.w3.org/2001/XMLSchema");
                writer.WriteEndAttribute();
                writer.WriteRaw(global::System.Xml.XmlConvert.ToString(((ulong)value)));
            }
            else if (__runtimeType == typeof(byte))
            {
                writer.WriteXmlnsAttribute(null, "http://www.w3.org/2001/XMLSchema");
                writer.WriteStartAttribute("i", "type", "http://www.w3.org/2001/XMLSchema-instance");
                writer.WriteQualifiedName("unsignedByte", "http://www.w3.org/2001/XMLSchema");
                writer.WriteEndAttribute();
                writer.WriteValue(((byte)value));
            }
            else
            {
                throw new global::System.Runtime.Serialization.SerializationException(
                    "Type '" + __runtimeType.FullName + "' cannot be written as an untyped array item.");
            }
        }

        private sealed class __ReferenceScope
        {
            private global::System.Collections.Generic.Dictionary<object, int> _ids;
            private global::System.Collections.Generic.HashSet<object> _byValueInScope;
            private int _next = 1;
            private int _depth;

            /// <summary>Depth past which a by-value graph starts being checked for cycles.</summary>
            private const int DepthToCheckCyclicReference = 512;

            /// <summary>Enters a contract written by value, throwing if it is already on the path.</summary>
            internal void EnterByValue(object value)
            {
                if (++_depth < DepthToCheckCyclicReference)
                {
                    return;
                }

                if (_byValueInScope == null)
                {
                    _byValueInScope = new global::System.Collections.Generic.HashSet<object>(
                        global::System.Collections.Generic.ReferenceEqualityComparer.Instance);
                }

                if (!_byValueInScope.Add(value))
                {
                    throw new global::System.Runtime.Serialization.SerializationException(
                        "Object graph for type '" + value.GetType().FullName + "' contains cycles and cannot be " +
                        "serialized if references are not tracked. Consider using the DataContractAttribute " +
                        "with the IsReference property set to true.");
                }
            }

            internal void ExitByValue(object value)
            {
                if (_depth >= DepthToCheckCyclicReference && _byValueInScope != null)
                {
                    _byValueInScope.Remove(value);
                }

                _depth--;
            }

            /// <summary>Returns true when z:Ref was written, meaning the content must not be repeated.</summary>
            internal bool WriteIdOrRef(global::System.Xml.XmlDictionaryWriter writer, object value)
            {
                if (_ids == null)
                {
                    _ids = new global::System.Collections.Generic.Dictionary<object, int>(
                        global::System.Collections.Generic.ReferenceEqualityComparer.Instance);
                }

                int id;
                if (_ids.TryGetValue(value, out id))
                {
                    writer.WriteAttributeString("z", "Ref", "http://schemas.microsoft.com/2003/10/Serialization/", Id(id));
                    return true;
                }

                id = _next++;
                _ids.Add(value, id);
                writer.WriteAttributeString("z", "Id", "http://schemas.microsoft.com/2003/10/Serialization/", Id(id));
                return false;
            }

            private static string Id(int id) =>
                "i" + id.ToString(global::System.Globalization.CultureInfo.InvariantCulture);
        }

        private sealed class __ReadScope
        {
            private global::System.Collections.Generic.Dictionary<string, object> _byId;

            /// <summary>Records an instance under its z:Id, before any of its members are read.</summary>
            /// <remarks>
            /// Before, not after. An instance inside its own graph is referred to while it is still
            /// being filled in - which is what a cycle is - so recording it late would turn a z:Ref
            /// into a lookup that fails. Mirrors AddNewObject, which upstream calls before
            /// deserializing members for the same reason.
            /// </remarks>
            internal void Add(string id, object value)
            {
                if (id == null)
                {
                    return;
                }

                if (_byId == null)
                {
                    _byId = new global::System.Collections.Generic.Dictionary<string, object>(
                        global::System.StringComparer.Ordinal);
                }

                _byId[id] = value;
            }

            internal object Get(string id)
            {
                if (_byId != null && _byId.TryGetValue(id, out object value))
                {
                    return value;
                }

                throw new global::System.Runtime.Serialization.SerializationException(
                    "Deserialized object with reference id '" + id + "' not found.");
            }
        }

        private static void WriteEnum(global::System.Xml.XmlDictionaryWriter writer, long longValue, long[] values, string[] names, bool isFlags, string typeName)
        {
            for (int i = 0; i < values.Length; i++)
            {
                if (longValue == values[i])
                {
                    writer.WriteString(names[i]);
                    return;
                }
            }

            if (isFlags)
            {
                int zeroIndex = -1;
                bool noneWritten = true;
                for (int i = 0; i < values.Length; i++)
                {
                    long current = values[i];
                    if (current == 0) { zeroIndex = i; continue; }
                    if (longValue == 0) { break; }
                    if ((current & longValue) == current)
                    {
                        if (noneWritten) { noneWritten = false; } else { writer.WriteString(" "); }
                        writer.WriteString(names[i]);
                        longValue &= ~current;
                    }
                }

                if (longValue != 0)
                {
                    throw new global::System.Runtime.Serialization.SerializationException("Invalid enum value on write for " + typeName + ".");
                }

                if (noneWritten && zeroIndex >= 0)
                {
                    writer.WriteString(names[zeroIndex]);
                }

                return;
            }

            throw new global::System.Runtime.Serialization.SerializationException("Invalid enum value on write for " + typeName + ".");
        }

        private static long ReadEnum(string text, long[] values, string[] names, bool isFlags, string typeName)
        {
            if (isFlags)
            {
                long flags = 0;
                int start = 0;
                for (int i = 0; i <= text.Length; i++)
                {
                    if (i == text.Length || text[i] == ' ')
                    {
                        if (i > start)
                        {
                            flags |= ReadEnumName(text, start, i - start, values, names, typeName);
                        }

                        start = i + 1;
                    }
                }

                return flags;
            }

            if (text.Length == 0)
            {
                throw new global::System.Runtime.Serialization.SerializationException("Invalid enum value '' cannot be deserialized into type " + typeName + ".");
            }

            return ReadEnumName(text, 0, text.Length, values, names, typeName);
        }

        private static long ReadEnumName(string text, int index, int count, long[] values, string[] names, string typeName)
        {
            for (int i = 0; i < names.Length; i++)
            {
                if (names[i].Length == count && string.CompareOrdinal(text, index, names[i], 0, count) == 0)
                {
                    return values[i];
                }
            }

            throw new global::System.Runtime.Serialization.SerializationException(
                "Invalid enum value '" + text.Substring(index, count) + "' cannot be deserialized into type " + typeName + ".");
        }

        // global::App.Marks
        private static readonly long[] __EnumValues0 = new long[] { 0L, 1L, 2L };
        private static readonly string[] __EnumNames0 = new string[] { "None", "Alpha", "Beta" };

        /// <summary>Writes the members of Bag, without a wrapping element.</summary>
        private static void __WriteContent0(global::System.Xml.XmlDictionaryWriter writer, global::App.Bag value, __ReferenceScope scope)
        {
            // Counts (Order = -1)
            writer.WriteStartElement("Counts", "http://schemas.datacontract.org/2004/07/App");
            writer.WriteXmlnsAttribute(null, "http://schemas.microsoft.com/2003/10/Serialization/Arrays");
            if (value.Counts == null)
            {
                WriteNil(writer);
            }
            else
            {
                foreach (var item in value.Counts)
                {
                    writer.WriteStartElement("int", "http://schemas.microsoft.com/2003/10/Serialization/Arrays");
                    writer.WriteValue(item);
                    writer.WriteEndElement();
                }
            }
            writer.WriteEndElement();

            // Flags (Order = -1)
            writer.WriteStartElement("Flags", "http://schemas.datacontract.org/2004/07/App");
            WriteEnum(writer, (long)value.Flags, __EnumValues0, __EnumNames0, true, "global::App.Marks");
            writer.WriteEndElement();

            // Map (Order = -1)
            writer.WriteStartElement("Map", "http://schemas.datacontract.org/2004/07/App");
            writer.WriteXmlnsAttribute(null, "http://schemas.microsoft.com/2003/10/Serialization/Arrays");
            if (value.Map == null)
            {
                WriteNil(writer);
            }
            else
            {
                foreach (var pair in value.Map)
                {
                    writer.WriteStartElement("KeyValueOfstringint", "http://schemas.microsoft.com/2003/10/Serialization/Arrays");
                    writer.WriteStartElement("Key", "http://schemas.microsoft.com/2003/10/Serialization/Arrays");
                    if (pair.Key == null)
                    {
                        WriteNil(writer);
                    }
                    else
                    {
                        writer.WriteValue(pair.Key);
                    }
                    writer.WriteEndElement();
                    writer.WriteStartElement("Value", "http://schemas.microsoft.com/2003/10/Serialization/Arrays");
                    writer.WriteValue(pair.Value);
                    writer.WriteEndElement();
                    writer.WriteEndElement();
                }
            }
            writer.WriteEndElement();

            // Rows (Order = -1)
            writer.WriteStartElement("Rows", "http://schemas.datacontract.org/2004/07/App");
            writer.WriteXmlnsAttribute(null, "http://schemas.microsoft.com/2003/10/Serialization/Arrays");
            if (value.Rows == null)
            {
                WriteNil(writer);
            }
            else
            {
                foreach (var item in value.Rows)
                {
                    writer.WriteStartElement("ArrayOfint", "http://schemas.microsoft.com/2003/10/Serialization/Arrays");
                    if (item == null)
                    {
                        WriteNil(writer);
                    }
                    else
                    {
                        foreach (var innerItem in item)
                        {
                            writer.WriteStartElement("int", "http://schemas.microsoft.com/2003/10/Serialization/Arrays");
                            writer.WriteValue(innerItem);
                            writer.WriteEndElement();
                        }
                    }
                    writer.WriteEndElement();
                }
            }
            writer.WriteEndElement();

            // Tags (Order = -1)
            writer.WriteStartElement("Tags", "http://schemas.datacontract.org/2004/07/App");
            writer.WriteXmlnsAttribute(null, "http://schemas.microsoft.com/2003/10/Serialization/Arrays");
            if (value.Tags == null)
            {
                WriteNil(writer);
            }
            else
            {
                foreach (var item in value.Tags)
                {
                    writer.WriteStartElement("string", "http://schemas.microsoft.com/2003/10/Serialization/Arrays");
                    if (item == null)
                    {
                        WriteNil(writer);
                    }
                    else
                    {
                        writer.WriteValue(item);
                    }
                    writer.WriteEndElement();
                }
            }
            writer.WriteEndElement();

            // Untyped (Order = -1)
            writer.WriteStartElement("Untyped", "http://schemas.datacontract.org/2004/07/App");
            writer.WriteXmlnsAttribute(null, "http://schemas.microsoft.com/2003/10/Serialization/Arrays");
            if (value.Untyped == null)
            {
                WriteNil(writer);
            }
            else
            {
                foreach (var item in value.Untyped)
                {
                    writer.WriteStartElement("anyType", "http://schemas.microsoft.com/2003/10/Serialization/Arrays");
                    WriteAnyType(writer, item);
                    writer.WriteEndElement();
                }
            }
            writer.WriteEndElement();
        }

        /// <summary>Reads the members of Bag into an existing instance.</summary>
        private static void __ReadContent0(global::System.Xml.XmlDictionaryReader reader, global::App.Bag value, __ReadScope scope)
        {
            int __matched = -1;
            while (reader.NodeType == global::System.Xml.XmlNodeType.Element)
            {
                if (__matched < 0
                    && reader.LocalName == "Counts"
                    && reader.NamespaceURI == "http://schemas.datacontract.org/2004/07/App")
                {
                    if (IsNil(reader))
                    {
                        reader.Skip();
                        value.Counts = default;
                    }
                    else
                    {
                        global::System.Collections.Generic.List<int> __items = new global::System.Collections.Generic.List<int>();
                        if (reader.IsEmptyElement)
                        {
                            reader.Read();
                        }
                        else
                        {
                            reader.ReadStartElement();
                            reader.MoveToContent();
                            while (reader.NodeType == global::System.Xml.XmlNodeType.Element)
                            {
                                int __item = default;
                                string __itemText = ReadText(reader);
                                if (__itemText == null)
                                {
                                    __item = default;
                                }
                                else
                                {
                                    __item = global::System.Xml.XmlConvert.ToInt32(__itemText);
                                }
                                __items.Add(__item);
                                reader.MoveToContent();
                            }

                            reader.ReadEndElement();
                        }

                        value.Counts = __items;
                    }
                    __matched = 0;
                }
                else if (__matched < 1
                    && reader.LocalName == "Flags"
                    && reader.NamespaceURI == "http://schemas.datacontract.org/2004/07/App")
                {
                    string __text = ReadText(reader);
                    if (__text == null)
                    {
                        value.Flags = default;
                    }
                    else
                    {
                        value.Flags = (global::App.Marks)ReadEnum(__text, __EnumValues0, __EnumNames0, true, "global::App.Marks");
                    }
                    __matched = 1;
                }
                else if (__matched < 2
                    && reader.LocalName == "Map"
                    && reader.NamespaceURI == "http://schemas.datacontract.org/2004/07/App")
                {
                    if (IsNil(reader))
                    {
                        reader.Skip();
                        value.Map = default;
                    }
                    else
                    {
                        global::System.Collections.Generic.Dictionary<string, int> __pairs = new global::System.Collections.Generic.Dictionary<string, int>();
                        if (reader.IsEmptyElement)
                        {
                            reader.Read();
                        }
                        else
                        {
                            reader.ReadStartElement();
                            reader.MoveToContent();
                            while (reader.NodeType == global::System.Xml.XmlNodeType.Element)
                            {
                                string __key = default;
                                int __value = default;

                                if (reader.IsEmptyElement)
                                {
                                    reader.Read();
                                }
                                else
                                {
                                    reader.ReadStartElement();
                                    reader.MoveToContent();
                                    int __part = -1;
                                    while (reader.NodeType == global::System.Xml.XmlNodeType.Element)
                                    {
                                        if (__part < 0
                                            && reader.LocalName == "Key"
                                            && reader.NamespaceURI == "http://schemas.microsoft.com/2003/10/Serialization/Arrays")
                                        {
                                            string __keyText = ReadText(reader);
                                            if (__keyText == null)
                                            {
                                                __key = default;
                                            }
                                            else
                                            {
                                                __key = __keyText;
                                            }
                                            __part = 0;
                                        }
                                        else if (__part < 1
                                            && reader.LocalName == "Value"
                                            && reader.NamespaceURI == "http://schemas.microsoft.com/2003/10/Serialization/Arrays")
                                        {
                                            string __valueText = ReadText(reader);
                                            if (__valueText == null)
                                            {
                                                __value = default;
                                            }
                                            else
                                            {
                                                __value = global::System.Xml.XmlConvert.ToInt32(__valueText);
                                            }
                                            __part = 1;
                                        }
                                        else
                                        {
                                            reader.Skip();
                                        }

                                        reader.MoveToContent();
                                    }

                                    reader.ReadEndElement();
                                }

                                __pairs.Add(__key, __value);
                                reader.MoveToContent();
                            }

                            reader.ReadEndElement();
                        }

                        value.Map = __pairs;
                    }
                    __matched = 2;
                }
                else if (__matched < 3
                    && reader.LocalName == "Rows"
                    && reader.NamespaceURI == "http://schemas.datacontract.org/2004/07/App")
                {
                    if (IsNil(reader))
                    {
                        reader.Skip();
                        value.Rows = default;
                    }
                    else
                    {
                        global::System.Collections.Generic.List<int[]> __items = new global::System.Collections.Generic.List<int[]>();
                        if (reader.IsEmptyElement)
                        {
                            reader.Read();
                        }
                        else
                        {
                            reader.ReadStartElement();
                            reader.MoveToContent();
                            while (reader.NodeType == global::System.Xml.XmlNodeType.Element)
                            {
                                int[] __item = default;
                                if (IsNil(reader))
                                {
                                    reader.Skip();
                                    __item = default;
                                }
                                else
                                {
                                    global::System.Collections.Generic.List<int> __inner = new global::System.Collections.Generic.List<int>();
                                    if (reader.IsEmptyElement)
                                    {
                                        reader.Read();
                                    }
                                    else
                                    {
                                        reader.ReadStartElement();
                                        reader.MoveToContent();
                                        while (reader.NodeType == global::System.Xml.XmlNodeType.Element)
                                        {
                                            int __innerItem = default;
                                            string __innerText = ReadText(reader);
                                            if (__innerText == null)
                                            {
                                                __innerItem = default;
                                            }
                                            else
                                            {
                                                __innerItem = global::System.Xml.XmlConvert.ToInt32(__innerText);
                                            }
                                            __inner.Add(__innerItem);
                                            reader.MoveToContent();
                                        }

                                        reader.ReadEndElement();
                                    }

                                    __item = __inner.ToArray();
                                }
                                __items.Add(__item);
                                reader.MoveToContent();
                            }

                            reader.ReadEndElement();
                        }

                        value.Rows = __items.ToArray();
                    }
                    __matched = 3;
                }
                else if (__matched < 4
                    && reader.LocalName == "Tags"
                    && reader.NamespaceURI == "http://schemas.datacontract.org/2004/07/App")
                {
                    if (IsNil(reader))
                    {
                        reader.Skip();
                        value.Tags = default;
                    }
                    else
                    {
                        global::System.Collections.Generic.List<string> __items = new global::System.Collections.Generic.List<string>();
                        if (reader.IsEmptyElement)
                        {
                            reader.Read();
                        }
                        else
                        {
                            reader.ReadStartElement();
                            reader.MoveToContent();
                            while (reader.NodeType == global::System.Xml.XmlNodeType.Element)
                            {
                                string __item = default;
                                string __itemText = ReadText(reader);
                                if (__itemText == null)
                                {
                                    __item = default;
                                }
                                else
                                {
                                    __item = __itemText;
                                }
                                __items.Add(__item);
                                reader.MoveToContent();
                            }

                            reader.ReadEndElement();
                        }

                        value.Tags = __items.ToArray();
                    }
                    __matched = 4;
                }
                else if (__matched < 5
                    && reader.LocalName == "Untyped"
                    && reader.NamespaceURI == "http://schemas.datacontract.org/2004/07/App")
                {
                    if (IsNil(reader))
                    {
                        reader.Skip();
                        value.Untyped = default;
                    }
                    else
                    {
                        global::System.Collections.ArrayList __items = new global::System.Collections.ArrayList();
                        if (reader.IsEmptyElement)
                        {
                            reader.Read();
                        }
                        else
                        {
                            reader.ReadStartElement();
                            reader.MoveToContent();
                            while (reader.NodeType == global::System.Xml.XmlNodeType.Element)
                            {
                                object __item = default;
                                if (IsNil(reader))
                                {
                                    reader.Skip();
                                    __item = default;
                                }
                                else
                                {
                                    __item = ReadAnyType(reader);
                                }
                                __items.Add(__item);
                                reader.MoveToContent();
                            }

                            reader.ReadEndElement();
                        }

                        value.Untyped = __items;
                    }
                    __matched = 5;
                }
                else
                {
                    reader.Skip();
                }

                reader.MoveToContent();
            }
        }

        /// <summary>Writes Bag in http://schemas.datacontract.org/2004/07/App.</summary>
        private sealed class __DataContractSerializer0 : global::CoreWCF.Runtime.Serialization.AotXmlObjectSerializer
        {
            private readonly global::System.Xml.XmlDictionaryString _name;
            private readonly global::System.Xml.XmlDictionaryString _ns;

            internal __DataContractSerializer0(global::System.Xml.XmlDictionaryString name, global::System.Xml.XmlDictionaryString ns)
            {
                _name = name;
                _ns = ns;
            }

            /// <inheritdoc />
            public override void WriteObject(global::System.Xml.XmlDictionaryWriter writer, object graph)
            {
                writer.WriteStartElement(_name, _ns);

                if (!string.Equals("http://schemas.datacontract.org/2004/07/App", _ns?.Value, global::System.StringComparison.Ordinal))
                {
                    writer.WriteXmlnsAttribute(null, "http://schemas.datacontract.org/2004/07/App");
                }

                writer.WriteXmlnsAttribute("i", "http://www.w3.org/2001/XMLSchema-instance");

                if (graph == null)
                {
                    WriteNil(writer);
                }
                else
                {
                    __ReferenceScope scope = new __ReferenceScope();
                    __WriteContent0(writer, (global::App.Bag)graph, scope);
                }

                writer.WriteEndElement();
            }

            /// <inheritdoc />
            public override bool CanReadObject => true;

            /// <inheritdoc />
            public override bool IsStartObject(global::System.Xml.XmlDictionaryReader reader)
            {
                reader.MoveToContent();
                return reader.IsStartElement(_name, _ns);
            }

            /// <inheritdoc />
            public override object ReadObject(global::System.Xml.XmlDictionaryReader reader, bool verifyObjectName)
            {
                reader.MoveToContent();

                if (verifyObjectName && !reader.IsStartElement(_name, _ns))
                {
                    throw new global::System.Runtime.Serialization.SerializationException(
                        "Expecting element '" + _name.Value + "' from namespace '" + _ns.Value + "'.");
                }

                if (IsNil(reader))
                {
                    reader.Skip();
                    return null;
                }

                __ReadScope scope = new __ReadScope();
                global::App.Bag result = default;

                global::App.Bag __typed = new global::App.Bag();
                if (reader.IsEmptyElement)
                {
                    reader.Read();
                }
                else
                {
                    reader.ReadStartElement();
                    reader.MoveToContent();
                    __ReadContent0(reader, __typed, scope);
                    reader.ReadEndElement();
                }

                result = __typed;

                return result;
            }
        }
    }
}

#nullable restore
